### PR TITLE
Py3k minor fixes

### PR DESCRIPTION
**Pull request by thanatos**
A small bundle of Python 3 compatibility fixes.

This represents all the small and simple Python 3 touchups required to get `letsencrypt --help` up and running. There's some slightly larger changes, but they will be in a separate PR.

### CODE REVIEW

**Comment by pde** [comment]
Travis hasn't tested the tip of this branch for some reason; closing an re-opening.

**Comment by thanatos** [comment]
> Travis hasn't tested the tip of this branch for some reason; closing an re-opening.

I've run into this before; it's Github, not Travis. (I consider this a bug in GitHub). If you inspect the parents on GitHub, you can tell — `76532f3` "Make uses of StringIO.StringIO Python 3 compatible" is the tip of the branch; GitHub isn't sorting the commits in DAG order.¹

<sub>¹They're sorted above by Author Date; I didn't cherry-pick them into the branch in the same order I authored them. On my side, these were all separate branches so that I could keep the commits discrete. I ended up combining this batch into a PR, as I figured a PR for each was too much. I have a script on my side that merges the outstanding branches together for me to test.</sub>

**Comment by pde** [comment]
LGTM.

**Comment by thanatos** [comment]
Thanks @pde! If you have a free moment, and don't mind, would you mind glancing at #2395? I fear it might have slipped past your gaze, and I'm hoping it's straightforward.

(Also, the tests fail — but I'm not sure if it's me.)

**Pull request merged**
