### PR TITLE
Keep storage.names() from passing None to open()

### PR DESCRIPTION
**Pull request by convissor**
Fixes exiting abnormally with:
    TypeError: coercing to Unicode: need string or buffer, NoneType found

### CODE REVIEW

**Comment by convissor** [comment]
The Travis CI failure was due to one of the four test jobs being unable to reach the test server.

**Comment by pde** [comment]
(Travis issue fixed)

Hi @convissor were you seeing this error occur in practice?  If so, under what circumstances?

**Comment by convissor** [comment]
Funny you ask.  Last night while falling asleep I thought, "hey, I should explain how to reproduce that." :)

Pick an existing certificate to renew.  Before renewing, rename or delete the `/etc/letsencrypt/live/<domain>` directory.  Then call letsencrypt.  I did it via `letsencrypt-auto certonly --webroot ...`, though I suspect it will happen under other plugins as well.

**Comment by bmw** [comment]
Just a thought, perhaps `RenewableCert` objects should have checks added to `__init__` to verify that the symlinks and their targets exist to prevent this and similar problems occurring in other functions as well.

**Comment by convissor** [comment]
That can be an additional check.  The check I added should stay because `current_target()` can return `None`.

**Comment by bmw** [comment]
I believe if we add the checks I suggested, `current_target` cannot return `None`.

**Comment by bmw** [comment]
This check doesn't hurt though. With that in mind, I'm merging this PR and opening a new issue to fix the problem in `__init__`.

Thanks for writing this up @convissor!

**Comment by pde** [comment]
Ah, that makes sense.  Probably in cases where there is a renewal configuration file that points to nonexistent things in `/etc/letsencrypt/live`, we should print a warning; if the user really, really wants to move stuff out of /etc/letsencrypt/live, maybe they want to either update or delete the renewal configuration file.

**Pull request merged**
