### PR TITLE
Multi cert chains (fixes #633).

### LINKED ISSUE #633: Handle multiple "up" links
After issuing a new cert, the client will get a link to the issuer cert using a link with rel="up". We expect that there will be multiple "up" links for the multiple intermediate certs. One intermediate cert will be signed by the ISRG Root. The other intermediate cert will be signed by the IdenTrust Root. In production rollout we'll want the client to choose the IdenTrust-signed intermediate, which will be trusted by real clients.

The client should probably fetch each issuer cert listed in an "up" link, parse it, and prioritize based on that intermediate's Issuer field, comparing it against a baked-in list of roots that it knows to be widely trusted.

### PR DESCRIPTION
**Pull request by kuba**
@schoen, could you have a look?

### CODE REVIEW

**Comment by kuba** [comment]
This needs some more work: https://travis-ci.org/letsencrypt/letsencrypt/jobs/79744170#L2777

**Comment by kuba** [comment]
Ready to review.

**Comment by schoen** [comment]
Hi @kuba, I'll take a look at this in a few minutes. Thank you!

**Comment by kuba** [comment]
@schoen?

**Comment by schoen** [comment]
Hi @kuba, isn't there one more `save_successor` use that needs to be updated, in `cli.py`?  It still has the old-style

```
        lineage.save_successor(
            lineage.latest_common_version(), OpenSSL.crypto.dump_certificate(
                OpenSSL.crypto.FILETYPE_PEM, new_certr.body),
            new_key.pem, OpenSSL.crypto.dump_certificate(
                OpenSSL.crypto.FILETYPE_PEM, new_chain))
```

which doesn't seem to be modified by your PR, but probably needs to be in the same way that the others are. (This is at line 898 in my current tree but probably a slightly different line number in master.) This one would also need to use `crypto_util.dump_pyopenssl_chain` instead of `OpenSSL.crypto.dump_certificate`, right?

**Comment by kuba** [comment]
I'm not sure which code you're referring to, @schoen. There might be some conflicts with your branch at #758...

**Comment by kuba** [comment]
ping?

**Comment by pde** [comment]
I can't see another call to save_successor, even with #758 merged.

**Comment by schoen** [comment]
@kuba, I apologize, I was grepping in my branch and not in master. I think @jdkasten is about to merge my branch, which will then have the obsolete invocation style of `save_successor` where I referred to (actually at line 188 of `cli.py`). You can fix that there or else I should be able to do it after #758.

**Pull request merged**
