### PR TITLE
Add developer switch in config

### PR DESCRIPTION
**Pull request by Mrnumbers9**

### CODE REVIEW

**Comment by Mrnumbers9** [comment]
Sorry I used true instead of True

**Comment by Mrnumbers9** [comment]
And i forgot again

**Comment by bmw** [comment]
Hi @Mrnumbers9. Thank you very much for looking into the project and taking the time to write this PR.

We actually have functionality similar to this already. If you include `--agree-eula` on the command line, the user will not be prompted to agree to the EULA before continuing (their agreement was specified on the command line).

Since we already have this functionality, I'm closing this PR. If I misunderstood what you were trying to do, please let me know. I'd happy to reopen the PR and help you to get it working with Travis.

**Comment by Mrnumbers9** [comment]
Ok

**Pull request closed without merging**
