### PR TITLE
Split docs (fixes #969)

### LINKED ISSUE #969: Sphinx docs no longer build off of PyPi
Well, this is a bit tricky.  Because the sphinx documentation build process reads the actual code to help generate the docs, we are seeing problems when using the tarballs that come out of PyPi.  The documentation makes references to code that's no longer shipped - letsencrypt_apache, letsencrypt_nginx, letsencrypt_compatibility_test, and letshelp_letsencrypt_*.

I'm not entirely sure how to solve this.  If we move the documentation that refers to the other modules into those tarballs and try to build it there, will it build correctly based on the code installed in the system paths?

@kuba, @fmarier, I'd love both of your input here.

Build log:
```
PYTHONPATH=. http_proxy='127.0.0.1:9' sphinx-build -N -bhtml docs/ build/html
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
WARNING: intersphinx inventory 'http://docs.python.org/objects.inv' not fetchable due to <class 'urllib2.URLError'>: <urlopen error [Errno 111] Connection refused>
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 39 source files that are out of date
updating environment: 39 added, 0 changed, 0 removed
reading sources... [  2%] api
reading sources... [  5%] api/account
reading sources... [  7%] api/achallenges
reading sources... [ 10%] api/auth_handler
reading sources... [ 12%] api/client
reading sources... [ 15%] api/configuration
reading sources... [ 17%] api/constants
reading sources... [ 20%] api/continuity_auth
reading sources... [ 23%] api/crypto_util
reading sources... [ 25%] api/display
reading sources... [ 28%] api/errors
reading sources... [ 30%] api/index
reading sources... [ 33%] api/interfaces
reading sources... [ 35%] api/le_util
reading sources... [ 38%] api/log
reading sources... [ 41%] api/plugins/common
reading sources... [ 43%] api/plugins/disco
reading sources... [ 46%] api/plugins/manual
reading sources... [ 48%] api/plugins/standalone
reading sources... [ 51%] api/proof_of_possession
reading sources... [ 53%] api/renewer
reading sources... [ 56%] api/reporter
reading sources... [ 58%] api/reverter
reading sources... [ 61%] api/storage
reading sources... [ 64%] contributing
reading sources... [ 66%] index
reading sources... [ 69%] intro
reading sources... [ 71%] man/jws
reading sources... [ 74%] man/letsencrypt
reading sources... [ 76%] man/letsencrypt-renewer
reading sources... [ 79%] pkgs
reading sources... [ 82%] pkgs/acme/index
reading sources... [ 84%] pkgs/acme/jose
reading sources... [ 87%] pkgs/letsencrypt_apache
reading sources... [ 89%] pkgs/letsencrypt_compatibility_test
reading sources... [ 92%] pkgs/letsencrypt_nginx
reading sources... [ 94%] pkgs/letshelp_letsencrypt
reading sources... [ 97%] plugins
reading sources... [100%] using

/<<PKGBUILDDIR>>/docs/contributing.rst:89: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'letsencrypt-nginx/tests/boulder-integration.sh'.
README.rst:20: WARNING: nonlocal image URI found: https://travis-ci.org/letsencrypt/letsencrypt.svg?branch=master
README.rst:20: WARNING: nonlocal image URI found: https://coveralls.io/repos/letsencrypt/letsencrypt/badge.svg?branch=master
README.rst:20: WARNING: nonlocal image URI found: https://readthedocs.org/projects/letsencrypt/badge/
README.rst:20: WARNING: nonlocal image URI found: https://quay.io/repository/letsencrypt/letsencrypt/status
README.rst:54: WARNING: nonlocal image URI found: https://travis-ci.org/letsencrypt/letsencrypt.svg?branch=master
README.rst:58: WARNING: nonlocal image URI found: https://coveralls.io/repos/letsencrypt/letsencrypt/badge.svg?branch=master
README.rst:62: WARNING: nonlocal image URI found: https://readthedocs.org/projects/letsencrypt/badge/
README.rst:66: WARNING: nonlocal image URI found: https://quay.io/repository/letsencrypt/letsencrypt/status
/<<PKGBUILDDIR>>/docs/man/jws.rst:1: ERROR: Command u'jws --help all' failed: [Errno 2] No such file or directory
/<<PKGBUILDDIR>>/docs/man/letsencrypt.rst:1: ERROR: Command u'letsencrypt --help all' failed: [Errno 2] No such file or directory
/<<PKGBUILDDIR>>/docs/man/letsencrypt-renewer.rst:1: ERROR: Command u'letsencrypt-renewer --help' failed: [Errno 2] No such file or directory
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:4: WARNING: autodoc: failed to import module u'letsencrypt_apache'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:10: WARNING: autodoc: failed to import module u'letsencrypt_apache.configurator'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache.configurator
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:16: WARNING: autodoc: failed to import module u'letsencrypt_apache.display_ops'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache.display_ops
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:22: WARNING: autodoc: failed to import module u'letsencrypt_apache.dvsni'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache.dvsni
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:28: WARNING: autodoc: failed to import module u'letsencrypt_apache.obj'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache.obj
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:34: WARNING: autodoc: failed to import module u'letsencrypt_apache.parser'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache.parser
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:41: WARNING: autodoc: failed to import module u'letsencrypt_apache.augeas_configurator'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache.augeas_configurator
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:4: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:10: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.errors'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.errors
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:16: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.interfaces'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.interfaces
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:22: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.test_driver'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.test_driver
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:28: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.util'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.util
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:34: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.configurators'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.configurators
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:40: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.configurators.apache'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.configurators.apache
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:46: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.configurators.apache.apache24'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.configurators.apache.apache24
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:52: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.configurators.apache.common'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.configurators.apache.common
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_nginx.rst:4: WARNING: autodoc: failed to import module u'letsencrypt_nginx'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_nginx
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_nginx.rst:10: WARNING: autodoc: failed to import module u'letsencrypt_nginx.configurator'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_nginx.configurator
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_nginx.rst:16: WARNING: autodoc: failed to import module u'letsencrypt_nginx.dvsni'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_nginx.dvsni
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_nginx.rst:22: WARNING: autodoc: failed to import module u'letsencrypt_nginx.obj'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_nginx.obj
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_nginx.rst:28: WARNING: autodoc: failed to import module u'letsencrypt_nginx.parser'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_nginx.parser
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_nginx.rst:34: WARNING: autodoc: failed to import module u'letsencrypt_nginx.nginxparser'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_nginx.nginxparser
/<<PKGBUILDDIR>>/docs/pkgs/letshelp_letsencrypt.rst:4: WARNING: autodoc: failed to import module u'letshelp_letsencrypt'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letshelp_letsencrypt
/<<PKGBUILDDIR>>/docs/pkgs/letshelp_letsencrypt.rst:10: WARNING: autodoc: failed to import module u'letshelp_letsencrypt.apache'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letshelp_letsencrypt.apache
/<<PKGBUILDDIR>>/docs/using.rst:168: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'examples/dev-cli.ini'.
looking for now-outdated files... none found
pickling environment... done
checking consistency... /<<PKGBUILDDIR>>/docs/man/jws.rst:: WARNING: document isn't included in any toctree
/<<PKGBUILDDIR>>/docs/man/letsencrypt.rst:: WARNING: document isn't included in any toctree
/<<PKGBUILDDIR>>/docs/man/letsencrypt-renewer.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [  2%] api
writing output... [  5%] api/account
writing output... [  7%] api/achallenges
writing output... [ 10%] api/auth_handler
writing output... [ 12%] api/client
writing output... [ 15%] api/configuration
writing output... [ 17%] api/constants
writing output... [ 20%] api/continuity_auth
writing output... [ 23%] api/crypto_util
writing output... [ 25%] api/display
writing output... [ 28%] api/errors
writing output... [ 30%] api/index
writing output... [ 33%] api/interfaces
writing output... [ 35%] api/le_util
writing output... [ 38%] api/log
writing output... [ 41%] api/plugins/common
writing output... [ 43%] api/plugins/disco
writing output... [ 46%] api/plugins/manual
writing output... [ 48%] api/plugins/standalone
writing output... [ 51%] api/proof_of_possession
writing output... [ 53%] api/renewer
writing output... [ 56%] api/reporter
writing output... [ 58%] api/reverter
writing output... [ 61%] api/storage
writing output... [ 64%] contributing
writing output... [ 66%] index
writing output... [ 69%] intro
writing output... [ 71%] man/jws
writing output... [ 74%] man/letsencrypt
writing output... [ 76%] man/letsencrypt-renewer
writing output... [ 79%] pkgs
writing output... [ 82%] pkgs/acme/index
writing output... [ 84%] pkgs/acme/jose
writing output... [ 87%] pkgs/letsencrypt_apache
writing output... [ 89%] pkgs/letsencrypt_compatibility_test
writing output... [ 92%] pkgs/letsencrypt_nginx
writing output... [ 94%] pkgs/letshelp_letsencrypt
writing output... [ 97%] plugins
writing output... [100%] using

generating indices... genindex py-modindex
highlighting module code... [  2%] acme.jose.errors
highlighting module code... [  5%] letsencrypt.reverter
highlighting module code... [  7%] acme.errors
highlighting module code... [ 10%] letsencrypt.configuration
highlighting module code... [ 12%] letsencrypt.reporter
highlighting module code... [ 15%] acme.jose.jws
highlighting module code... [ 17%] letsencrypt.client
highlighting module code... [ 20%] acme.client
highlighting module code... [ 23%] acme.fields
highlighting module code... [ 25%] acme.challenges
highlighting module code... [ 28%] letsencrypt.storage
highlighting module code... [ 30%] letsencrypt.display.enhancements
highlighting module code... [ 33%] letsencrypt.log
highlighting module code... [ 35%] letsencrypt.le_util
highlighting module code... [ 38%] letsencrypt.renewer
highlighting module code... [ 41%] letsencrypt.plugins.manual
highlighting module code... [ 43%] acme.jose.jwa
highlighting module code... [ 46%] letsencrypt.auth_handler
highlighting module code... [ 48%] letsencrypt.display.util
highlighting module code... [ 51%] acme.jose.b64
highlighting module code... [ 53%] acme.messages
highlighting module code... [ 56%] letsencrypt.proof_of_possession
highlighting module code... [ 58%] namedtuple_Key
highlighting module code... [ 61%] letsencrypt.crypto_util
highlighting module code... [ 64%] acme.jose.interfaces
highlighting module code... [ 66%] letsencrypt.display.ops
highlighting module code... [ 69%] acme.jose.util
highlighting module code... [ 71%] acme.other
highlighting module code... [ 74%] acme.jose.json_util
highlighting module code... [ 76%] acme.jose.jwk
highlighting module code... [ 79%] letsencrypt.interfaces
highlighting module code... [ 82%] letsencrypt.account
highlighting module code... [ 84%] letsencrypt.plugins.common
highlighting module code... [ 87%] letsencrypt.continuity_auth
highlighting module code... [ 89%] namedtuple_CSR
highlighting module code... [ 92%] letsencrypt.plugins.disco
highlighting module code... [ 94%] letsencrypt.achallenges
highlighting module code... [ 97%] letsencrypt.plugins.standalone.authenticator
highlighting module code... [100%] letsencrypt.errors

writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 41 warnings.
PYTHONPATH=. http_proxy='127.0.0.1:9' sphinx-build -N -bman docs/ build/man
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
WARNING: intersphinx inventory 'http://docs.python.org/objects.inv' not fetchable due to <class 'urllib2.URLError'>: <urlopen error [Errno 111] Connection refused>
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 39 added, 0 changed, 0 removed
reading sources... [  2%] api
reading sources... [  5%] api/account
reading sources... [  7%] api/achallenges
reading sources... [ 10%] api/auth_handler
reading sources... [ 12%] api/client
reading sources... [ 15%] api/configuration
reading sources... [ 17%] api/constants
reading sources... [ 20%] api/continuity_auth
reading sources... [ 23%] api/crypto_util
reading sources... [ 25%] api/display
reading sources... [ 28%] api/errors
reading sources... [ 30%] api/index
reading sources... [ 33%] api/interfaces
reading sources... [ 35%] api/le_util
reading sources... [ 38%] api/log
reading sources... [ 41%] api/plugins/common
reading sources... [ 43%] api/plugins/disco
reading sources... [ 46%] api/plugins/manual
reading sources... [ 48%] api/plugins/standalone
reading sources... [ 51%] api/proof_of_possession
reading sources... [ 53%] api/renewer
reading sources... [ 56%] api/reporter
reading sources... [ 58%] api/reverter
reading sources... [ 61%] api/storage
reading sources... [ 64%] contributing
reading sources... [ 66%] index
reading sources... [ 69%] intro
reading sources... [ 71%] man/jws
reading sources... [ 74%] man/letsencrypt
reading sources... [ 76%] man/letsencrypt-renewer
reading sources... [ 79%] pkgs
reading sources... [ 82%] pkgs/acme/index
reading sources... [ 84%] pkgs/acme/jose
reading sources... [ 87%] pkgs/letsencrypt_apache
reading sources... [ 89%] pkgs/letsencrypt_compatibility_test
reading sources... [ 92%] pkgs/letsencrypt_nginx
reading sources... [ 94%] pkgs/letshelp_letsencrypt
reading sources... [ 97%] plugins
reading sources... [100%] using

/<<PKGBUILDDIR>>/docs/contributing.rst:89: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'letsencrypt-nginx/tests/boulder-integration.sh'.
README.rst:20: WARNING: nonlocal image URI found: https://travis-ci.org/letsencrypt/letsencrypt.svg?branch=master
README.rst:20: WARNING: nonlocal image URI found: https://coveralls.io/repos/letsencrypt/letsencrypt/badge.svg?branch=master
README.rst:20: WARNING: nonlocal image URI found: https://readthedocs.org/projects/letsencrypt/badge/
README.rst:20: WARNING: nonlocal image URI found: https://quay.io/repository/letsencrypt/letsencrypt/status
README.rst:54: WARNING: nonlocal image URI found: https://travis-ci.org/letsencrypt/letsencrypt.svg?branch=master
README.rst:58: WARNING: nonlocal image URI found: https://coveralls.io/repos/letsencrypt/letsencrypt/badge.svg?branch=master
README.rst:62: WARNING: nonlocal image URI found: https://readthedocs.org/projects/letsencrypt/badge/
README.rst:66: WARNING: nonlocal image URI found: https://quay.io/repository/letsencrypt/letsencrypt/status
/<<PKGBUILDDIR>>/docs/man/jws.rst:1: ERROR: Command u'jws --help all' failed: [Errno 2] No such file or directory
/<<PKGBUILDDIR>>/docs/man/letsencrypt.rst:1: ERROR: Command u'letsencrypt --help all' failed: [Errno 2] No such file or directory
/<<PKGBUILDDIR>>/docs/man/letsencrypt-renewer.rst:1: ERROR: Command u'letsencrypt-renewer --help' failed: [Errno 2] No such file or directory
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:4: WARNING: autodoc: failed to import module u'letsencrypt_apache'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:10: WARNING: autodoc: failed to import module u'letsencrypt_apache.configurator'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache.configurator
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:16: WARNING: autodoc: failed to import module u'letsencrypt_apache.display_ops'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache.display_ops
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:22: WARNING: autodoc: failed to import module u'letsencrypt_apache.dvsni'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache.dvsni
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:28: WARNING: autodoc: failed to import module u'letsencrypt_apache.obj'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache.obj
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:34: WARNING: autodoc: failed to import module u'letsencrypt_apache.parser'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache.parser
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_apache.rst:41: WARNING: autodoc: failed to import module u'letsencrypt_apache.augeas_configurator'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_apache.augeas_configurator
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:4: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:10: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.errors'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.errors
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:16: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.interfaces'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.interfaces
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:22: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.test_driver'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.test_driver
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:28: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.util'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.util
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:34: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.configurators'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.configurators
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:40: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.configurators.apache'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.configurators.apache
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:46: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.configurators.apache.apache24'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.configurators.apache.apache24
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_compatibility_test.rst:52: WARNING: autodoc: failed to import module u'letsencrypt_compatibility_test.configurators.apache.common'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_compatibility_test.configurators.apache.common
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_nginx.rst:4: WARNING: autodoc: failed to import module u'letsencrypt_nginx'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_nginx
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_nginx.rst:10: WARNING: autodoc: failed to import module u'letsencrypt_nginx.configurator'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_nginx.configurator
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_nginx.rst:16: WARNING: autodoc: failed to import module u'letsencrypt_nginx.dvsni'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_nginx.dvsni
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_nginx.rst:22: WARNING: autodoc: failed to import module u'letsencrypt_nginx.obj'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_nginx.obj
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_nginx.rst:28: WARNING: autodoc: failed to import module u'letsencrypt_nginx.parser'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_nginx.parser
/<<PKGBUILDDIR>>/docs/pkgs/letsencrypt_nginx.rst:34: WARNING: autodoc: failed to import module u'letsencrypt_nginx.nginxparser'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letsencrypt_nginx.nginxparser
/<<PKGBUILDDIR>>/docs/pkgs/letshelp_letsencrypt.rst:4: WARNING: autodoc: failed to import module u'letshelp_letsencrypt'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letshelp_letsencrypt
/<<PKGBUILDDIR>>/docs/pkgs/letshelp_letsencrypt.rst:10: WARNING: autodoc: failed to import module u'letshelp_letsencrypt.apache'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named letshelp_letsencrypt.apache
/<<PKGBUILDDIR>>/docs/using.rst:168: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'examples/dev-cli.ini'.
looking for now-outdated files... none found
pickling environment... done
checking consistency... /<<PKGBUILDDIR>>/docs/man/jws.rst:: WARNING: document isn't included in any toctree
/<<PKGBUILDDIR>>/docs/man/letsencrypt.rst:: WARNING: document isn't included in any toctree
/<<PKGBUILDDIR>>/docs/man/letsencrypt-renewer.rst:: WARNING: document isn't included in any toctree
done
writing... letsencrypt.7 { intro using contributing plugins api api/account api/achallenges api/auth_handler api/client api/configuration api/constants api/continuity_auth api/crypto_util api/display api/errors api/index api/interfaces api/le_util api/log api/plugins/common api/plugins/disco api/plugins/manual api/plugins/standalone api/proof_of_possession api/renewer api/reporter api/reverter api/storage pkgs pkgs/acme/index pkgs/acme/jose pkgs/letsencrypt_apache pkgs/letsencrypt_compatibility_test pkgs/letsencrypt_nginx pkgs/letshelp_letsencrypt } letsencrypt.1 { } letsencrypt-renewer.1 { } jws.1 { } 
build succeeded, 41 warnings.
````

### PR DESCRIPTION
**Pull request by kuba**
Please excuse huge diff - most of it is boilerplate (that cannot be symlinked due to PyPI tarballs contraints). I would like to have it merged before next dev release to ease Debian packaging.

@hlieberman, @fmarier: does it work for you? :)

### CODE REVIEW

**Comment by kuba** [comment]
@bmw, could you have a look? :)

**Comment by pde** [comment]
Assigning Harlan in case he can confirm that this is ok, but a +1 from anyone is fine.

**Comment by hlieberman** [comment]
@kuba: docs/conf.py, line 317, syntax error.

Also, letsencrypt-apache and letsencrypt-nginx are going to break because of the references to source code.  I might be able to fix that on my side, though, so don't hold the merge for that.

**Comment by pde** [comment]
Rebased onto master and merged with @hlieberman's fix.

**Pull request closed without merging**
