### PR TITLE
Fix some pep8 warnings

### PR DESCRIPTION
**Pull request by ArchimedesPi**

### CODE REVIEW

**Comment by kuba** [comment]
lgtm

**Comment by bmw** [comment]
LGTM. The only other `pep8` complaint I get locally is:
```
letsencrypt/cli.py:551:46: E226 missing whitespace around arithmetic operator
```
Perhaps this should be fixed as well, but regardless, this removes all other `pep8` problems. Thanks again @ArchimedesPi!

**Comment by ArchimedesPi** [comment]
I didn't fix that one because the code is
```
reordered = args[:i] + args[i+1:] + [args[i]]
```
which wouldn't look good when fixed as
```
reordered = args[:i] + args[i + 1:] + [args[i]]
```

**Comment by kuba** [comment]
I personally prefer the last version (IMHO actually the only that is accepted by `pylint`, `pep8` and `PEP8`).

**Pull request merged**
