### PR TITLE
Remove renewer.py

### PR DESCRIPTION
**Pull request by bmw**
If we ever want this, we can look at the old release tags.

### CODE REVIEW

**Comment by pde** [comment]
LGTM.

**Comment by marcan** [comment]
What's the replacement for this? I've been using it (and working around its quirks) on my servers for a while, and just deployed LE on another one today and had to roll back my tree to keep using it.

**Comment by schoen** [comment]
Sorry for the change; the replacement is meant to be

https://github.com/letsencrypt/letsencrypt/pull/2338

in the upcoming 0.4.0 release. This is integrated into the client and
handles preservation of renewal configuration options better.

**Comment by marcan** [comment]
I had a quick look and it looks good. I'll stick with an older commit for now, until that's merged in.

**Pull request merged**
