### PR TITLE
ManualAuthenticator -> Authenticator

### PR DESCRIPTION
**Pull request by kuba**
Step towards unifying plugin class names (new standalone, or current `null.Installer` also follow this scheme).

### CODE REVIEW

**Comment by kuba** [comment]
Notably, this will require to reinstall the core: `pip install -e .` in order to update the entry point.

**Comment by bmw** [comment]
LGTM! Thanks @kuba.

**Comment by pde** [comment]
This broke the client completely.  Reverted.

**Comment by pde** [comment]
The error was:

```
ubuntu@ip-172-31-3-78:~/letsencrypt$ venv/bin/letsencrypt --help
An unexpected error occurred.
ImportError: <module 'letsencrypt.plugins.manual' from '/home/ubuntu/letsencrypt/letsencrypt/plugins/manual.py'> has no 'ManualAuthenticator' attribute
Please see the logfile 'letsencrypt.log' for more details.
```

**Comment by bmw** [comment]
@pde, did you see https://github.com/letsencrypt/letsencrypt/pull/833#issuecomment-143419559?

**Comment by pde** [comment]
Nope!  @kuba we really need run / install scripts; these kinds of changes waste large amounts of developer time :(

**Comment by kuba** [comment]
Did you "fix" it on `master` without creating a PR (6f1b1570b13d9e41dceaca909ebf417469609ee7)? :O Please don't do that... there are many reasons, but the most obvious one here is:  if you created a PR, someone would quickly notice what's your problem.

If we had install scripts you would have to be somehow notified that you need to run them. This particular change caused our binary not to load, so... I just suggest you follow the commit log: GitHub emails and/or manually before `git pull`. Also, if it passed tests, then it really suggests your local problem.

Maybe try pining someone on IRC next time if all above fails?

**Pull request merged**
