### PR TITLE
Ignore renewal configs that don't end in .conf

### PR DESCRIPTION
**Pull request by schoen**
Pretty trivial fix to #2254.

(Maybe be missing test coverage for one new line; let's see.)

### CODE REVIEW

**Comment by pde** [comment]
LGTM

**Comment by pde** [comment]
Correction: do add the test coverage if you can do so quickly.

**Comment by pde** [comment]
Oh, hmmm, it seems you do have coverage?  What's lying around in that directory that you skip?

**Comment by schoen** [comment]
I just added the test coverage.

**Comment by pde** [comment]
Great.

**Pull request merged**
