### PR TITLE
nginx: Only insert directive if its not already in block

### LINKED ISSUE #942: Nginx parser needs add_or_set_server_directives
Right now Nginx's parser has an add_server_directives method, with a `replace` parameter. If `replace` is true, the directive must already exist in the config, and it will be replaced. If `replace` is false, the directive is added regardless of what exists in the config.

Since most directives are not allowed repeatedly, what we want in many cases is an `add_or_set_server_directives`, which will replace a directive if it's present*, and add it if it's not present.

*To be really tidy, we should say: If the directive is present with the correct value, leave it alone, i.e. don't change its location in the config.

### PR DESCRIPTION
**Pull request by bit**
fixes #942

### CODE REVIEW

**Comment by pde** [comment]
@erikrose this looks like a big win for two lines of code, but I haven't read the nginx codebase so I'm going to wait for your +1 to merge.

**Comment by erikrose** [comment]
Having a look now. (Need to bone up on nginx syntax; it's been a long time.)

**Comment by erikrose** [comment]
I don't see anything that could go wrong because of it, though I'd like to see the invisible "else" case covered with a test and the docstring updated.

**Comment by bit** [comment]
ok, added modified test to check that adding existing blocks works and updated docstring.

**Comment by erikrose** [comment]
Thanks! +1 for merge, @pde.

**Comment by pde** [comment]
Great! Merging.

**Pull request merged**
