### PR TITLE
added: --webroot-domain-path domain:path [needs revision]

### PR DESCRIPTION
**Pull request by grubberr**
one of possible solutions for this #1016

added new option 

```
--webroot-domain-path domain:path
```

for example:

```
./bin/letsencrypt auth ... --authenticator webroot \
  --domains domain1.com --webroot-domain-path domain1.com:/home/user/public_html \
  --domains domain2.com --webroot-domain-path domain2.com:/home/user/public_html/domain2
```

old invocation also works

```
./bin/letsencrypt auth ... --authenticator webroot \
  --domains domain1.com --webroot-path /home/user/public_html
```

### CODE REVIEW

**Comment by kuba** [comment]
I would rather prefer `--webroot-path "default/path/if/nothing/specific/given, domain1.com:specific/path/to/domain1, domain2:specific/path/to/domain2"` syntax:
- config file doesn't allow value to be specified multiple times
- no need to create a brand new flag, `--webroot-path` can be overloaded
- `--webroot-path foo` still has the same meaning
- you can specify default value for domains that share common `public_html`

Good way to approach it is to decode comma/colon-separated string inside `manual.Autenticator.paths`, by defining new `@property` that operates over `self.conf("path")`.

@grubberr, do you think you could work towards this solution?

**Comment by grubberr** [comment]
@kuba ok I will re-implement according to your requirements

**Comment by kuba** [comment]
@grubberr, thank you very much! Welcome to the project! :)

**Comment by kuba** [comment]
Please remove `[needs revision]` from the title when you're done.

**Comment by grubberr** [comment]
closed because of #1284

**Pull request closed without merging**
