### PR TITLE
Downgrade a very excitable security comment to an XXX

### PR DESCRIPTION
**Pull request by pde**
Resolves: #1400

Also note that this function will need to become more sophisticated as we
support autoupdating of config options (eg those changed in #1390)

### CODE REVIEW

**Comment by bmw** [comment]
I'm merging this since it's only really an aesthetic/comment change and has no effect on program execution.

@jdkasten, we'd love your thoughts here to know if there is a real security vuln here that we're not thinking of and these changes should be reverted.

**Comment by jdkasten** [comment]
This is performing the duty of a package manager.

It is not a problem as we no longer check for privilege escalation. (That
is exactly what this is)

Apache configs are Turing complete... so whoever has access to the file has
complete root access to your system.

You are free to do what you want with the info though.

**Comment by bmw** [comment]
It's true that if someone modified `options-ssl-apache.conf`, `letsencrypt` will blindly copy and include that file in Apache. It's also true that `options-ssl-apache.conf` has the same permissions as our all of our Python files so an attacker could just modify our code to do whatever they want. This is at least the case when cloning this repo or when the files are installed using `letsencrypt-auto`.

In general, I think if an attacker is able to modify any files installed with `letsencrypt`, the user is pretty much screwed and I don't think there is much we can do to defend against that. Let me know if I'm thinking about this the wrong way.

**Comment by jdkasten** [comment]
Yep, you are correct, the current installation path already assumes that to
be the case.

The comment was outdated and should be removed.

**Pull request merged**
