### PR TITLE
Replace "python" with "python2"

### PR DESCRIPTION
**Pull request by bmw**
`python` should be `python2` since Python 2 is not the default on all systems (e.g. Arch Linux).

### CODE REVIEW

**Comment by jmhodges** [comment]
This doesn't work on OS X which may also have python2.7.

**Comment by jmhodges** [comment]
That was a terrible comment. bmw reached out to me and I gave more context: namely that *sometimes* OS X users don't have a python2 binary (in fact, the default OS X has only /usr/bin/python and it's still python 2.6!) but do have a python2.7 binary (which they can get through MacPorts).

It's really sucky.

We put a hack in boulder's tests to check for the obvious stuff but I'm not sure it covers all the bases. https://github.com/letsencrypt/boulder/blob/master/test.sh#L96

**Comment by bmw** [comment]
So we have the benefit that we are already running Python and can look up the path to the interpreter with `sys.executable`. New commit uses that as well as `distutils.spawn.find_executable` to only use the basename of the path if possible.

**Comment by kuba** [comment]
Note that the client and manual commands are likely to be run on different machines, probably with different Python setups. The autodiscovery as proposed in f7dbaab breaks this workflow.

Since `manual` mode is designed for more advanced users, they should be able to easily review and fix the commands (including the path to `python` binary) before running them. Other solution would be to autodiscover Python in the shell script presented to the user (so that it is run on target machine).

There are systems that don't have `python2` binary at all, e.g. Debian squeeze (see [docs](http://letsencrypt.readthedocs.org/en/latest/using.html#debian)).

**Comment by bmw** [comment]
@kuba, you're right. Originally, I was going to put the autodiscovery in the shell script but I didn't think about the case where the client was run on a different machine. I'll submit a new commit for this later today.

**Pull request closed without merging**
