### PR TITLE
When permissions don't work (maybe you're root), disable a unit test that assumes permissions work

### PR DESCRIPTION
**Pull request by pde**
Fixes: #1979

### CODE REVIEW

**Comment by joohoi** [comment]
Are we actually checking if we're root (title of PR), or if we have too broad privileges to begin with?

If we're supposed to check only if we're root, shouldn't os.geteuid() do the trick?

**Comment by pde** [comment]
I guess I didn't want to test for the hypothesised cause of the problem, but for evidence that it was always occurring.  Will re-title the PR :)

**Comment by pde** [comment]
For instance, I don't fully understand how debian's `fakeroot` tool works and how it would interact with `os.geteuid()`

**Comment by joohoi** [comment]
I personally like to work with files using 'with open as', but that's only preference. LGTM

**Comment by pde** [comment]
Taking @joohoi's suggestion, and merging.

**Pull request merged**
