### PR TITLE
Add support for optional trailing period in FQDNs

### LINKED ISSUE #2065: FQDN passed with a trailing period is not valid.
```
Requesting root privileges to run with virtualenv: ~/.local/share/letsencrypt/bin/letsencrypt run --apache --email ...@....... --redirect --agree-tos -d mysubdomain.mydomain.io.
Requested domain is not a FQDN
```

It is valid to refer to a domain using the trailing period, and I had expected letsencrypt would handle it as such too.

### PR DESCRIPTION
**Pull request by filipochnik**
Fixes #2065

### CODE REVIEW

**Comment by kuba** [comment]
Have you actually tested it against Boulder (e.g. testing instance)?

**Comment by filipochnik** [comment]
Right, my bad. Can you tell me how to do that/point to the docs?

**Comment by kuba** [comment]
Easiest way to do that is to use staging API endpoint by using `--staging`

**Comment by filipochnik** [comment]
Thanks! Turns out it's not supported on the Boulder side.
`letsencrypt certonly --test-cert --text --webroot --webroot-path /tmp --email mail@test.com -d www.test.com. --staging`
fails with
`The request message was malformed :: Error creating new authz :: DNS label is too short`

I'll file an issue on the Boulder's repo.

**Comment by pde** [comment]
I doubt that one actually wants a cert with a trailing period in its names; there are bound to be client implementations out there that choke on such certs.  Would anything go wrong if the client just stripped the trailing dot to re-normalise the name?

**Comment by pde** [comment]
The Decentralized SSL Observatory has seen about 13,000 certs with names that end in a dot.  However it's only ever seen one such certificate that's valid in browsers, a cert for `webmail.` that was signed by Calvados and was valid from 2012-2013.

**Comment by filipochnik** [comment]
Makes sense. I'm closing this PR then, I'll submit a new one with proper fix.

**Pull request closed without merging**
