### PR TITLE
Apache with more than one vhost (fixes #809)

### LINKED ISSUE #809: Apache install fails with two vhosts
When I run `letsencrypt install --cert-path /etc/letsencrypt/live/example.com/cert.pem --key-path /etc/letsencrypt/live/example.com/privkey.pem --chain-path /etc/letsencrypt/live/example.com/chain.pem` with the following configuration https://drive.google.com/file/d/0B9CrBQYK660GRm1EVVFoQzdIRFE/view?usp=sharing, installation fails. The reason for this is the dummy directives including things like `insert_cert_file_path` and `insert_key_file_path` are not removed before restarting Apache, causing it to fail.

### PR DESCRIPTION
**Pull request by SwartzCr**
Added interstitial saves to apache changes which fixed but when multiple vhosts were specified

The final save still gets called an sets a checkpoint

### CODE REVIEW

**Comment by SwartzCr** [comment]
fixes problem in issue #809

**Comment by pde** [comment]
Nice. @jdkasten can you sign off on this?

**Comment by bmw** [comment]
I can confirm this fixes the issue I reported in #809. LGTM.

**Comment by jdkasten** [comment]
Thanks @SwartzCr and @bmw!  This is the solution we thought would work yesterday, thanks for implementing it and testing it out.

**Pull request merged**
