### PR TITLE
Fix DST caused 1 hour offset in parse_time_interval() function

### PR DESCRIPTION
**Pull request by devnsec-com**
The `parse_time_interval()` function was using `time.localtime()` and `time.mktime()` functions, which will use local time zone and DST settings, in some circumstances it will result in 1 hour offset.

This PR will fix this bug by using GMT (aka UTC) time instead of local time.

### CODE REVIEW

**Comment by pde** [comment]
LGTM

**Comment by kuba** [comment]
Is it possible to write unit test that would catch an 1 hour offset error? To be honest, I don't think that either old or new code make much sense to me :(

**Comment by devnsec-com** [comment]
@kuba I've added the unit test for it.

BTW, I agree with you, the current implementation of this function still looks wrong for me.
For an example, if today is Jan 1, 2000, and the input of the function is `"1 year"`, what's the expected output? I would say `366`, but actually it will give me `365`, because it always use the time offset based on `1970-01-01T00:00:00+0000`.

**Comment by devnsec-com** [comment]
I've created a new PR #1144 to replace this one.

**Comment by schoen** [comment]
@devnsec-com, I'm going to merge #1144 -- thanks!

**Pull request closed without merging**
