### PR TITLE
Use PEM for Account.id generation.

### LINKED ISSUE #1012: cryptography==0.8 breaks client
Follow-up from https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203405#c17. It seems that our `cryptography>=0.8` requirement is too weak. After `pip install cryptography==0.8` the following error is thrown:

```
Traceback (most recent call last):
  File "/root/letsencrypt/venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1.0.dev0', 'console_scripts', 'letsencrypt')()
  File "/root/letsencrypt/letsencrypt/cli.py", line 1002, in main
    return args.func(args, config, plugins)
  File "/root/letsencrypt/letsencrypt/cli.py", line 376, in auth
    le_client = _init_le_client(args, config, authenticator, installer)
  File "/root/letsencrypt/letsencrypt/cli.py", line 160, in _init_le_client
    acc, acme = _determine_account(args, config)
  File "/root/letsencrypt/letsencrypt/cli.py", line 147, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/root/letsencrypt/letsencrypt/client.py", line 98, in register
    acc = account.Account(regr, key)
  File "/root/letsencrypt/letsencrypt/account.py", line 60, in __init__
    format=serialization.PublicFormat.SubjectPublicKeyInfo)
  File "/root/letsencrypt/venv/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 614, in public_bytes
    self._rsa_cdata
  File "/root/letsencrypt/venv/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1199, in _public_key_bytes
    raise ValueError("Only PEM encoding is supported by this backend")
ValueError: Only PEM encoding is supported by this backend
```

### PR DESCRIPTION
**Pull request by kuba**
This is a breaking change, already existing /etc/letsencrypt/accounts will cause the client raise `errors.AccountStorageError` ("Account ids mismatch ..."). Simple fix: start over by `rm -rf /etc/letsencrypt`. In a long run it's a better solution that bumping to `cryptography>=0.9`...

@pde, this is one of the examples that shows problem in sharing `/etc/letsencrypt` between our package and e.g. Debian packaging. Even if we had a migration script, if user went back to `letsencrypt` provided by Debian, they would have a really hard time.

Fixes #1012

### CODE REVIEW

**Comment by kuba** [comment]
Build affected by #1010.

**Comment by bmw** [comment]
Why is this a better solution than bumping to `cryptography>=0.9`? The bump seems like a simpler fix and doesn't require an account wipe for people that already received certs from production.

**Comment by kuba** [comment]
Because that makes our dependencies tighter, and hence the entire project is likely harder to package (some systems might not have `cryptography==0.9` packaged, but they might do have `cryptography==0.8`). If we can change our code to relax deps, then that's better for us. And we are still before launch so impact on users is low...

**Comment by pde** [comment]
Because we have a growing userbase, including some people with soon-to-be-real certs, we should no longer land changes that require an account wipe.

Before it can land, this PR needs a DER-to-PEM converter added to it, so that even with 0.8 installed the client uses the current on-disk format.  It's fine if that converter is implemented in a hackish manner (Popen `openssl x509 -inform PEM -outform DER` for instance), since the entire purpose of this is compatibility during the period when OSes have a too-old version of python-cryptography.

**Comment by kuba** [comment]
Correction after review of the code: customers will not see any errors and wipe is not really necessary - the only thing that changes is more DEBUG logs: https://github.com/letsencrypt/letsencrypt/blob/3885a40c421636805a77a0f1c573d1727169eddb/letsencrypt/account.py#L162. Client will happily create new account with new id. Problems might happen if using `--account ID`. FYI certificates are not bound to a particular account on the client side.

**Comment by kuba** [comment]
Another correction: `letsencrypt-renewer` does tie account to a lineage.

**Comment by pde** [comment]
OK, we can probably live with those debug logs and some extra-account-creation amongst the current userbase.  But we should test that before shipping a release.

**Comment by jsha** [comment]
I think bumping the cryptogrpahy dep to 0.9 is a good short-term fix, and we can re-add cryptography 0.8 support later if we need.

Note that if you want to calculate the SPKI hash without depending on cryptogrpahy 0.9 you can do it by shelling out to openssl: https://raymii.org/s/articles/HTTP_Public_Key_Pinning_Extension_HPKP.html

``
openssl x509 -noout -in certificate.pem -pubkey | \
openssl asn1parse -noout -inform pem -out public.key;
openssl dgst -sha256 -hex public.key
```

**Comment by jsha** [comment]
Another way to maintain compatibility would be to take the PEM output and run it through base64 decode to get the DER, then hash that. I really don't like the idea of moving to a key id method that depends on hashing the PEM.

That said, if we're going to break compatibility, can we also switch the hash to something other than md5?

**Comment by kuba** [comment]
I mostly thinking about packaging now. E.g. `jessie-backports` has only `0.8`. FreeBSD packagers also had issues https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203405#c17. Shelling out will cause us even more troubles.

**Comment by kuba** [comment]
Point about `md5` is that it is short (it's a filename, accessible by users); collisions are very unlikely to happen anyway and we don't need any other crypto property for it.

**Comment by pde** [comment]
Hmmm, what about:

https://docs.python.org/2/library/ssl.html#ssl.PEM_cert_to_DER_cert

**Comment by pde** [comment]
Will that work with a key, or not?

**Comment by pde** [comment]
(Seems the answer is no)

**Comment by pde** [comment]
Overall: @jsha I think you have a somewhat reasonable point about hashing PEM, but I don't think it's a good use of our time today to engineer something else :/.

**Comment by jsha** [comment]
Alright, given that we can write code to migrate people to whatever directory layout we want in the future, I'm fine with landing this as a quick fix. Another thought, perhaps for future tweaks: why not use the registration id, or even a locally incrementing number, as the name for this directory?

**Comment by pde** [comment]
OK, landing.

**Pull request merged**
