### PR TITLE
Pin parsedatetime version < 2.0

### PR DESCRIPTION
**Pull request by bmw**

### CODE REVIEW

**Comment by bmw** [comment]
Issue on parsedatetime reported at bear/parsedatetime#156.

**Comment by schoen** [comment]
Hopefully upstream will fix this and we won't need this change. Maybe they can even fix it before Travis finishes! :-)

**Comment by bmw** [comment]
Looks like Travis won the race, although I don't think we can blame upstream too much about that.

**Comment by schoen** [comment]
Sure enough!

**Comment by schoen** [comment]
Good luck to upstream in any case - maybe we can revert this pin soon.

**Pull request merged**
