### PR TITLE
Highly experimental Amazon Linux bootstrapping

### PR DESCRIPTION
**Pull request by pde**
(Not to be merged until after **1.0 for launch** is done, and after testing for impact on other RedHat based platforms).
Closes: #1458

### CODE REVIEW

**Comment by centminmod** [comment]
so not available yet https://community.letsencrypt.org/t/install-fails-on-amazon-linux/3708/6 ?

**Comment by pde** [comment]
@centminmod if some people show up here and say that they've tested this branch (and tested impact on RHEL systems) we can merge it.

Commented on the community thread, too.

**Comment by pde** [comment]
Actually, I have a feeling it's now safer to merge this than not, given that we took #1508 which may bump some systems over from using py26 to py27.  So merging.

**Comment by robwent** [comment]
HI, I just tested this on an Amazon ami after finding the forum post and it's not working for me.

I git clone the repo
`git checkout amazonlinux`
`./letsencrypt-auto --apache --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview --debug`

then get the message:

`Updating letsencrypt and virtual environment dependencies......Command "/root/.local/share/letsencrypt/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-DUvd68/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-dnN00O-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-DUvd68/cffi`

**Comment by robwent** [comment]
When I try and install python-cffi manually I get the following:

`/usr/lib/python2.6/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement python-cffi (from versions: )
  No matching distribution found for python-cffi`

**Comment by patf** [comment]
@robwent: I noticed you are using the amazonlinux branch. From what I can see all commits in that branch have been merged into master. It could be that you're running into some issue that has already been fixed in master - can you switch and try again?

**Comment by robwent** [comment]
Hi, 
I'm still getting the same after `git checkout master`

running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/c
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DUSE__THREAD -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/root/.local/share/letsencrypt/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-GfxhRO/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wpk0gQ-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-GfxhRO/cffi

I tried updating pip and a few other dependencies, but my understanding is that it creates it's own virtual environment which doesn't depend on the current system?

**Comment by patf** [comment]
The apache installer is currently only available on debian-based systems AFAIK. However, I don't think that's related to your error message (at least I got a different error when I attempted to run letsencrypt with --apache on my instance).

I tried to reproduce a similar bug posted on the community forum earlier today. I posted the commands I used (and which succeeded) here: https://community.letsencrypt.org/t/letsencrypt-auto-openssl-module-not-found-ec2/4356/2?u=pfg
Maybe you can spot the difference somewhere.

**Comment by robwent** [comment]
I get the error directly after that command rather than anything running.

`[root@ip-172-30-0-91 letsencrypt]# ./letsencrypt-auto --debug --nginx
Updating letsencrypt and virtual environment dependencies......Command "/root/.local/share/letsencrypt/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-1djPmm/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Bfx9X0-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-1djPmm/cffi
`

I'm using nginx as a webserver(doh) but get the same issues with the --nginx flag.

I'll try removing everything and starting again.
From some of the other notes in the community: I have openssl installed, have opened port 443 and told nginx to listen on it. Using curl I can see it connects but then closes the conection as it can't find any certs. Trying a page in a browser gets a connection refused message.

**Comment by robwent** [comment]
I just removed /root/.local/share and the previous git clone and ran again with the commands from your post but get the same errors.

I'm running the commands as root rather than sudoing if that makes any difference?

**Comment by patf** [comment]
nginx installer isn't shipped with the client by default (and I'm not sure about non-debian compatibility).

Anyhow, the error you're getting happens way before any installer is invoked (and definitely before any challenge requests are hitting your nginx). I'd suggest certonly with webroot mode once the client works.

I re-ran my commands as root inside of /root/ on a new, clean instance without any issues. Looks like the error is somehow tied to your specific configuration, or possibly something that's leftover from earlier clients (possibly from the slightly outdated `amazonlinux` branch).

I would suggest moving this to community forums until we confirm it's something that can be fixed in the client, since it doesn't seem to be related to the original issue here.

**Comment by robwent** [comment]
Ok, thanks for your help.
I'll keep an eye on the community, but am planning to start a new server when php 7 is available so may have another go then.

**Comment by johnlabarge** [comment]
I have the same issues with Amazon Linux  - any insights?

**Comment by henricavalcante** [comment]
Someone has success on Amazon Linux?

**Comment by rdunlop** [comment]
On Amazon Linux 2014-09.

I had problems with 
> Command "/home/ec2-user/.local/share/letsencrypt/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-dasaFg/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-cMMN5k-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/.local/share/letsencrypt/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-dasaFg/cffi`

Which I troubleshot further using `./letsencrypt --debug -v`.

Which showed me 
` c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>`

Which I resolved using `sudo yum install python27-devel`


Now it says:
`Version: 1.1-20080819
No installers are available on your OS yet; try running "letsencrypt-auto certonly" to get a cert you can install manually`

I'm proceeding with attempting to use the `certonly --webroot` path...

**Pull request merged**
