### PR TITLE
Apache conf tests in travis

### PR DESCRIPTION
**Pull request by pde**
* `tox -e apacheconftest` now works
* `.travis.yml` runs it

### CODE REVIEW

**Comment by pde** [comment]
Strangely, this last commit has failed integration tests with a DNS timeout at least four times...

**Comment by pde** [comment]
@jsha @jmhodges @rolandshoemaker just flagging that this PR seems to contain something that's exacerbating the DNS query timeout problem in our integration tests.  Those fail maybe 70% of the time in this branch.

**Comment by pde** [comment]
OK, I'm disabling this test in travis for now, but landing this PR so that we have the latest `tox -e apacheconftest` available in master.

**Comment by pde** [comment]
Merging this without the travis enablement (I think this had a review from joohoi, but also doesn't touch anything user-facing).

**Comment by jmhodges** [comment]
This went in without a code review from another team member. I thought we weren't doing that anymore.

**Pull request merged**
