### PR TITLE
Guard reverter invocations and wrap in correct exceptions

### PR DESCRIPTION
**Pull request by olabini**

### CODE REVIEW

**Comment by pde** [comment]
Assigning @bmw for review since he did similar work for Apache.

**Comment by olabini** [comment]
Any thoughts on this one?

**Comment by pde** [comment]
LGTM, but would still like @bmw to take a look since he has more experience with this aspect of plugins...

**Comment by bmw** [comment]
I'm planning on reviewing this PR this week. Sorry for the delay.

**Comment by bmw** [comment]
This PR wraps `ReverterError`s as `PluginErrors`s and improves save notes. This is kind of nice so I'm merging this PR but it makes no progress on #1977. I'll comment in #1977 of what needs to be done to resolve that issue.

LGTM

**Pull request merged**
