### PR TITLE
The actual 0.1.1 release

### PR DESCRIPTION
**Pull request by pde**
Due to bug #1966, the previous v0.1.1 tag was missing a version change to
letsencrypt/__init__.py this commit and the v0.1.1-corrected tag are the code
that was signed and uploaded to PyPI.

### CODE REVIEW

**Comment by pde** [comment]
Not sure what's going on with these test failures; the tests are passing for me locally on both of these commits, and at this point I do not see the string 0.2.0 anywhere in the tree...

**Comment by kuba** [comment]
So are you telling me that you uploaded some random tag (that you haven't even tested) rather than the actual code that was used in the release? :( https://github.com/letsencrypt/letsencrypt/releases/tag/v0.1.1-corrected points at edd20a8... I think I just lost any trust in the release process of this software, I'm afraid.

**Comment by pde** [comment]
No I tested the tag locally before uploading, and I currently believe it is fine (when I download the tarball of the tag from github, tests pass).  Not sure what travis is doing, yet...

**Comment by kuba** [comment]
Tag that you uploaded does not contain 9d50c3e from this PR...

**Comment by kuba** [comment]
https://github.com/letsencrypt/letsencrypt/issues/2019#issuecomment-167263396

**Pull request closed without merging**
