### PR TITLE
Recovery contact

### PR DESCRIPTION
**Pull request by Hainish**

### CODE REVIEW

**Comment by Hainish** [comment]
Unit tests have yet to be written - not sure if I'll have time for this

**Comment by pde** [comment]
@Hainish do you need someone else to try to shepherd this over the line to mergeability?

**Comment by jdkasten** [comment]
@Hainish @pde I am mostly through finishing this up... I will push what I
have to a separate branch.

**Comment by jdkasten** [comment]
Building off of this branch https://github.com/letsencrypt/lets-encrypt-preview/tree/recovery_contact

**Comment by jsha** [comment]
Does this branch need updating or has it been superseded?

**Comment by jdkasten** [comment]
It needs updating and needs to be finished. The spec has changed
significantly since this was started.

**Comment by jdkasten** [comment]
Trying to clean up the repo.  Closing this PR, though the commits live on in the recovery_contact branch.

**Pull request closed without merging**
