### PR TITLE
Plugin documentation (fixes #1137)

### LINKED ISSUE #1137: Narrative documentation for plugins
While changes proposed in #1079 help, it is very hard to tell from the names `manual`, `standalone`, and `webroot` what our plugins actually do. We need to add narrative documentation for each plugin to help people understand the purpose of each plugin and when they should be used.

### PR DESCRIPTION
**Pull request by bmw**

### CODE REVIEW

**Comment by pde** [comment]
I suggest documenting the flags used for each plugin, and which ones only work with `certonly`.  If you land #1547, you can include `--webroot` :)

**Comment by bmw** [comment]
I was actually finishing writing a comment on #1547 before I merged it when you landed commits on top of it that I had a nit about!

**Comment by bmw** [comment]
Ready for re-review.

**Comment by bmw** [comment]
letsencrypt/boulder#756 strikes again! [log](https://gist.github.com/bmw/8c3cfb10e8fc1eeb5398) is available here.

**Comment by pde** [comment]
Great!

**Pull request merged**
