### PR TITLE
Augeas Lens fix for Section Headings V2

### PR DESCRIPTION
**Pull request by bmw**
We enabled some additional tests that found a problem with the fix in #2530. Opening this again for tracking purposes.

### CODE REVIEW

**Comment by domcleal** [comment]
It looks like the Augeas parsing is OK, but the file can't pass the Apache config test as the includes don't exist.  Should the Include line be commented out some of the other passing files, or changed to IncludeOptional?

<pre>
02:26:30,053:ERROR:letsencrypt.le_util:Error while running apache2ctl configtest. Action 'configtest' failed. The Apache error log may have more information. apache2: Syntax error on line 237 of /etc/apache2/apache2.conf: Syntax error on line 73 of /etc/apache2/sites-enabled/section-continuations-2525.conf: Include directory '/etc/httpd/conf/plesk.conf.d/ip_default' not found
</pre>

**Comment by pde** [comment]
@domcleal yes I'd probably just comment out those lines unless you think they're important to the test.

**Comment by bmw** [comment]
Nonexistent includes are the reason tests fail on `section-continuations-2525.conf`, but this PR introduces testing failures on other configuration files which currently pass in `master`.

[failure 1](https://travis-ci.org/letsencrypt/letsencrypt/jobs/111372847#L862)
[failure 2](https://travis-ci.org/letsencrypt/letsencrypt/jobs/111372847#L866)

**Comment by bmw** [comment]
Thanks @domcleal! That fixed the problem. I'll fix the includes in `section-continuations-2525.conf` so we can get this merged.

**Comment by pde** [comment]
LGTM

**Pull request merged**
