### PR TITLE
Python 2.6 and 3.3+ support

### PR DESCRIPTION
**Pull request by kuba**
I really don't think 13 line change should stop us from supporting Python 2.6 throughout and 3.3+ in `acme`. Note that those have been disabled quite long time ago and the code is almost 100% compliant. Previous efforts to make code base portable were just too much work and they shouldn't have been discarded that easily.

It's clear that people expect `acme` to work with Python 3 (c.f. #928) and it's a real pain that Travis doesn't check such silly small things. Apparently current setup was meant to make things easier for me, but it's the opposite. Turning Py3 switch in `tox` shouldn't affect anyone else, apart from me.

Travis builds are parallel, so it does not increase the total build time, contrary to https://github.com/letsencrypt/letsencrypt/pull/630#issuecomment-140599598.

If it really slows down the development of anyone in the team, just ignore Travis Py 2.6 build failure, and I'll fix stuff myself, but at least let's keep a track of the compatibility status.

This PR will also allow me to release py3 wheels to PyPI.

### CODE REVIEW

**Comment by kuba** [comment]
Coincidentally, py2.6 job was affected by some Travis scheduling bug:
```
There was an error with the connection to the VM.
Your job will be requeued shortly...............
```

@bmw, could you kick https://travis-ci.org/letsencrypt/letsencrypt/jobs/84869803?

**Comment by bmw** [comment]
kicked

**Comment by kuba** [comment]
@bmw, thank you very much :)

Travis green.

**Comment by kuba** [comment]
Hah, see also #962.

**Comment by pde** [comment]
This will be merged at GA time, but we're going to leave it out until then to save developers time fixing python2isms and waiting longer for travis.

**Comment by kuba** [comment]
Ready to merge.

**Comment by bmw** [comment]
LGTM

**Pull request merged**
