### PR TITLE
CentOS add check for python tools and pip

### LINKED ISSUE #1823: CentOS 7 install misses python pieces
I have a [detailed post here](http://mangolassi.it/topic/7127/setting-up-letsencrypt-on-a-centos-7-nginx-proxy) on the issue.

If you are on a clean CentOS 7 minimal install the setup has problems because it does not include `python-tools` and `python-pip`

### PR DESCRIPTION
**Pull request by sorvani**
fixes #1823
Add check for python-tools and python-pip

### CODE REVIEW

**Comment by sorvani** [comment]
The Travis error seems to have nothing to do with my change. not sure why it is in error.

**Comment by pde** [comment]
Flagging this for 0.2.0 though we can land sooner if test farming can be done sooner.

**Comment by pde** [comment]
```
time python multitester.py targets.yaml ~/.ssh/pde-amazon2.pem pde scripts/test_letsencrypt_auto_certonly_standalone.sh --branch 1824
Making local dir for test repo and logs: letest-1453237839
[localhost] local: mkdir letest-1453237839
Making local git repo
Testing branch 1824 of https://github.com/letsencrypt/letsencrypt.git
[localhost] local: if [ -d letsencrypt ]; then rm -rf letsencrypt; fi
[localhost] local: git clone https://github.com/letsencrypt/letsencrypt.git --branch 1824 --single-branch
Cloning into 'letsencrypt'...
remote: Counting objects: 26492, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 26492 (delta 2), reused 4 (delta 1), pack-reused 26484
Receiving objects: 100% (26492/26492), 7.10 MiB | 3.19 MiB/s, done.
Resolving deltas: 100% (18722/18722), done.
Checking connectivity... done.
[localhost] local: tar czf le.tar.gz letsencrypt
Testing against these images: [14 total]
ami-26d5af4c ubuntu15.10
ami-d92e6bb3 ubuntu15.04LTS
ami-7b89cc11 ubuntu14.04LTS
ami-9295d0f8 ubuntu14.04LTS_32bit
ami-0611546c ubuntu12.04LTS
ami-116d857a debian8.1
ami-e0efab88 debian7.8.aws.1
ami-e6eeaa8e debian7.8.aws.1_32bit
ami-60b6c60a amazonlinux-2015.09.1
ami-0d4cfd66 amazonlinux-2015.03.1
ami-a8d369c0 RHEL7
ami-518bfb3b fedora23
ami-61bbf104 centos7
ami-57cd8732 centos6
Connecting to EC2 using
 profile pde
 keyname pde-amazon2
 keyfile /home/pde/.ssh/pde-amazon2.pem
Making Security Group
  letsencrypt_test already exists
Requesting Instances...
Found existing boulder server: ec2.Instance(id='i-cdf4af4c')
Creating instances: le-ubuntu15.10 le-ubuntu15.04LTS le-ubuntu14.04LTS le-ubuntu14.04LTS_32bit le-ubuntu12.04LTS le-debian8.1 le-debian7.8.aws.1 le-debian7.8.aws.1_32bit le-amazonlinux-2015.09.1 le-amazonlinux-2015.03.1 le-RHEL7 le-fedora23 le-centos7 le-centos6 
Waiting on Boulder Server
 server ec2.Instance(id='i-cdf4af4c')
Boulder Server at (SSH): ubuntu@54.209.116.22
Boulder Server at (public ip): http://54.209.116.22:4000/directory
Boulder Server at (EC2 private ip): http://172.31.54.176:4000/directory
Uploading and running test script in parallel: scripts/test_letsencrypt_auto_certonly_standalone.sh
Output routed to log files in letest-1453237839
[localhost] local: rm le.tar.gz
0 ubuntu15.10 pass
1 ubuntu15.04LTS pass
2 ubuntu14.04LTS pass
3 ubuntu14.04LTS_32bit pass
4 ubuntu12.04LTS pass
5 debian8.1 pass
6 debian7.8.aws.1 pass
7 debian7.8.aws.1_32bit pass
8 amazonlinux-2015.09.1 pass
9 amazonlinux-2015.03.1 pass
10 RHEL7 pass
11 fedora23 pass
12 centos7 pass
```

**Comment by pde** [comment]
LGTM, though this will need to be ported as #1665 is about to land...

**Comment by erikrose** [comment]
Closing this in favor of #2266.

**Pull request closed without merging**
