### PR TITLE
feature: --webroot-path 'default-path, domain1:path1, domain2:path2'

### PR DESCRIPTION
**Pull request by grubberr**
This is continuation of #1259 which I closed because of code mess in my old repo.
I have re-implemented like we discussed in #1259
now only one original command line option --webroot-path
which was improved to allow getting more complex path

1)
```
--webroot-path some-path   # old format still works
```

2)
```
--webroot-path 'default-path, domain1:path1, domain2:path2'
--webroot-path 'domain1:path1, domain2:path2'
```

new possible formats which allow to specify more specific domain path
and ( or ) default-path

#### Complex parsing in _parse_path_argument(self, path):
I am not sure about _parse_path_argument function
probably it looks pretty over engineered
the main idea why this so complex
I wanted to allow possibility to pass webroot pathes which contain 'spaces' or ':', etc

for example

```
--webroot-path 'homelinux.ga:/home/user/public_html/a\ b' # domain path which contains 'space' symbol
--webroot-path '/home/user/public_html/a\\:c' # default path which contains colon
```

### CODE REVIEW

**Comment by kuba** [comment]
Sorry for not getting to you back earlier and unfortunately I still don't have time to review it. At first glance, though, it looks massively over-engineered :(. There are no unit tests either

**Comment by kuba** [comment]
For anyone else interested in webroot: you might want to try https://github.com/kuba/simp_le instead. It supports multiple SANs and renewal.

**Comment by pde** [comment]
Hi @grubberr I think what @kuba really means when he says "over engineered" is that because neither `:` nor `,` are valid DNS characters, it should be safe to do something along the lines of:

```
entries = ",".split(config.domains)
for e in entires:
    domain, webroot = ":".split(e)
```
etc.  (Though it's worth noting that if we ever want to support certs for IPv6 addresses, ":" will be an issue.)

**Comment by pde** [comment]
More fundamentally, there's a question of how to structure these arguments.  Kuba's approach in `simp_le` is better than trying to squeeze both the default and a bunch of domain <-> webroot mappings into a single command line flag.  But I actually think we can do better still, if we can get argparse to tell us the relative positions of multiple webroot arguments.  Something like this:

`letsencrypt --webroot -w /var/www/example -d example.com -d www.example.com -w /var/www/preposterous -d preposterous.net -d www.preposterous.net`.

That will save the user a lot of typing.

**Comment by pde** [comment]
I've implemented that alternative in #1594 , though I was able to helpfully crib from @grubberr's work in a few places.

**Comment by bmw** [comment]
Thanks for the PR @grubberr, but since #1594 landed, this is no longer necessary.

**Pull request closed without merging**
