### PR TITLE
lens update from augeas upstream

### PR DESCRIPTION
**Pull request by pde**
From: https://github.com/hercules-team/augeas/pull/329
 Fixes: https://github.com/letsencrypt/letsencrypt/issues/1294#issuecomment-161805063

### CODE REVIEW

**Comment by pde** [comment]
@domcleal @jdkasten it seems that your lens patch breaks our tests because we declare that [this file](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/tests/testdata/debian_apache_2_4/two_vhost_80/apache2/conf-available/bad_conf_file.conf) should error out.  In a quick test, Apache seems to run with that file, but won't server things from it even if I add a DocumentRoot?  That's kind of weird behaviour.  Do others get the same result?

**Comment by domcleal** [comment]
The file works for me under EL7's httpd-2.4.6, and trying to change the case of other section tags in Apache configs seems to make no difference, it accepts them.

It might just need a different test to keep aecb7b71 working, perhaps a missing end tag?

**Comment by bmw** [comment]
It took a bit of work, but I was able to get this file to work with Apache 2.4.10 on Debian 8. Made the modification suggested by @domcleal to fix the test.

**Comment by pde** [comment]
Merging!

**Pull request merged**
