### PR TITLE
 Use reserved example domains in examples of shell commands. [needs revision]

### PR DESCRIPTION
**Pull request by rwetzlmayr**
Refs #1713.

### CODE REVIEW

**Comment by pde** [comment]
One downside of this is that it becomes less immediately clear to the reader that these are different domains.  It's a pity the RFCs don't seem to include any reserved examples that look very different from each other (there are some for IDNs but that's not really helpful).

**Comment by chriscroome** [comment]
Use some sub-domains, `thing.example.com`, `otherthing.example.com`, `yetanotherthing.example.net`?

**Comment by schoen** [comment]
I think @chriscroome's suggestion would make this more useful to the reader because it addresses @pde's objection.

**Comment by bmw** [comment]
fixed in #2452

**Pull request closed without merging**
