### PR TITLE
none should be None

### LINKED ISSUE #2709: authenticator/installer is set to "none"
This gets put into the renewal config file which will not be restored correctly. The correct value is "None".

### PR DESCRIPTION
**Pull request by bmw**
Fixes #2709

### CODE REVIEW

**Comment by schoen** [comment]
That is indeed a very simple PR! :smile:

Is there any known issue with code trying to reinstantiate plugins on the basis of renewal configs that somehow does *better* with `none` than with `None`?

**Comment by bmw** [comment]
> Is there any known issue with code trying to reinstantiate plugins on the basis of renewal configs that somehow does better with none than with None?

Not that I'm aware of.

**Comment by schoen** [comment]
OK, hopefully we'll become aware of them if there turn out to be any!

**Comment by schoen** [comment]
LGTM.

**Pull request merged**
