### PR TITLE
poll_and_ri: handle STATUS_INVALID, add max_attempts (fixes #1634)

### LINKED ISSUE #1634: poll_and_request_issuance loops forever on failure
In https://github.com/letsencrypt/letsencrypt/blob/master/acme/acme/client.py#L326, we only check for STATUS_VALID. We should also check for STATUS_INVALID and return once that happens, or there will be many clients looping forever making requests to the server.

Similarly, that method should have a timeout.

### PR DESCRIPTION
**Pull request by kuba**
Fixes #1634

### CODE REVIEW

**Comment by kuba** [comment]
cc: @jsha

**Comment by jsha** [comment]
LGTM. I'll leave it to a more active client developer to do the final review and merge. Thanks for fixing, @kuba!

**Comment by jsha** [comment]
BTW: reminder to put the "fixes #XXX" in the body rather than the title. This makes it clickable, and makes GitHub auto-resolve the issue on merge. I've edited this PR to move it.

**Comment by kuba** [comment]
@jsha, my experience shows that GitHub recognizes any of those three:
- PR title
- PR body
- commit description (first line or body)

**Comment by bmw** [comment]
LGTM. Thanks @kuba!

**Pull request merged**
