### PR TITLE
Removes py26reqs.txt and git dependency

### PR DESCRIPTION
**Pull request by bmw**
Supercedes #1661.

### CODE REVIEW

**Comment by pde** [comment]
First test run failed, but that wasn't this PR's fault.  Will try it after a merge from master later tonight.

```
python multitester.py targets.yaml $KEY $USERNAME scripts/test_leauto_upgrades.sh  --branch py26
/usr/lib/python2.7/dist-packages/cffi/model.py:526: UserWarning: 'point_conversion_form_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
Making local dir for test repo and logs: letest-1450230763
[localhost] local: mkdir letest-1450230763
Making local git repo
Testing branch py26 of https://github.com/letsencrypt/letsencrypt.git
[localhost] local: if [ -d letsencrypt ]; then rm -rf letsencrypt; fi
[localhost] local: git clone https://github.com/letsencrypt/letsencrypt.git --branch py26 --single-branch
Cloning into 'letsencrypt'...
remote: Counting objects: 23610, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 23610 (delta 5), reused 5 (delta 4), pack-reused 23594
Receiving objects: 100% (23610/23610), 6.40 MiB | 357.00 KiB/s, done.
Resolving deltas: 100% (16593/16593), done.
Checking connectivity... done.
[localhost] local: tar czf le.tar.gz letsencrypt
Testing against these images: [14 total]
ami-26d5af4c ubuntu15.10
ami-d92e6bb3 ubuntu15.04LTS
ami-7b89cc11 ubuntu14.04LTS
ami-9295d0f8 ubuntu14.04LTS_32bit
ami-0611546c ubuntu12.04LTS
ami-116d857a debian8.1
ami-e0efab88 debian7.8.aws.1
ami-e6eeaa8e debian7.8.aws.1_32bit
ami-60b6c60a amazonlinux-2015.09.1
ami-0d4cfd66 amazonlinux-2015.03.1
ami-a8d369c0 RHEL7
ami-518bfb3b fedora23
ami-61bbf104 centos7
ami-57cd8732 centos6
Connecting to EC2 using
 profile pde
 keyname pde-amazon2
 keyfile /home/pde/.ssh/pde-amazon2.pem
Making Security Group
  letsencrypt_test already exists
Requesting Instances...
Waiting on Boulder Server
 server ec2.Instance(id='i-6916c4d8')
Configuring and Launching Boulder
Boulder Server at (SSH): ubuntu@52.90.75.208
[ubuntu@52.90.75.208] put: scripts/boulder_config.sh -> /home/ubuntu/boulder_config.sh
[ubuntu@52.90.75.208] run: ./boulder_config.sh 
[ubuntu@52.90.75.208] out: ++ curl -s http://169.254.169.254/2014-11-05/meta-data/public-hostname
[ubuntu@52.90.75.208] out: + public_host=ec2-52-90-75-208.compute-1.amazonaws.com
[ubuntu@52.90.75.208] out: ++ curl -s http://169.254.169.254/2014-11-05/meta-data/public-ipv4
[ubuntu@52.90.75.208] out: + public_ip=52.90.75.208
[ubuntu@52.90.75.208] out: ++ curl -s http://169.254.169.254/2014-11-05/meta-data/local-ipv4
[ubuntu@52.90.75.208] out: + private_ip=172.31.50.127
[ubuntu@52.90.75.208] out: ++ grep nameserver /etc/resolv.conf
[ubuntu@52.90.75.208] out: ++ cut '-d ' -f2
[ubuntu@52.90.75.208] out: ++ head -1
[ubuntu@52.90.75.208] out: + resolver_ip=172.31.0.2
[ubuntu@52.90.75.208] out: + resolver=172.31.0.2:53
[ubuntu@52.90.75.208] out: + cd /home/ubuntu/gocode/src/github.com/letsencrypt/boulder
[ubuntu@52.90.75.208] out: + sed -i '/listenAddress/ s/127.0.0.1:4000/172.31.50.127:4000/' ./test/boulder-config.json
[ubuntu@52.90.75.208] out: + sed -i '/baseURL/ s/127.0.0.1:4000/172.31.50.127:4000/' ./test/boulder-config.json
[ubuntu@52.90.75.208] out: + sed -i '/httpPort/ s/5002/80/' ./test/boulder-config.json
[ubuntu@52.90.75.208] out: + sed -i '/httpsPort/ s/5001/443/' ./test/boulder-config.json
[ubuntu@52.90.75.208] out: + sed -i '/tlsPort/ s/5001/443/' ./test/boulder-config.json
[ubuntu@52.90.75.208] out: + sed -i '/dnsResolver/ s/127.0.0.1:8053/172.31.0.2:53/' ./test/boulder-config.json
[ubuntu@52.90.75.208] out: 

[ubuntu@52.90.75.208] run: go run cmd/rabbitmq-setup/main.go -server amqp://localhost
[ubuntu@52.90.75.208] run: nohup ./start.py >& /dev/null < /dev/null &
[ubuntu@52.90.75.208] out: [1] 2404
[ubuntu@52.90.75.208] out: 

....................Boulder Server at (public ip): http://52.90.75.208:4000/directory
Boulder Server at (EC2 private ip): http://172.31.50.127:4000/directory
Uploading and running test script in parallel: scripts/test_leauto_upgrades.sh
Output routed to log files in letest-1450230763

Fatal error: run() received nonzero return code 1 while executing!

Requested: ./test_leauto_upgrades.sh 
Executed: /bin/bash -l -i -c "export PUBLIC_IP=\"52.23.229.231\" PIP_EXTRA_INDEX_URL=\"https://certainly.isnot.org/pip/\" PRIVATE_IP=\"172.31.53.152\" PUBLIC_HOSTNAME=\"ec2-52-23-229-231.compute-1.amazonaws.com\" OS_TYPE=\"centos\" BOULDER_URL=\"http://172.31.50.127:4000/directory\" && ./test_leauto_upgrades.sh "

Aborting.

Fatal error: run() received nonzero return code 1 while executing!

Requested: ./test_leauto_upgrades.sh 
Executed: /bin/bash -l -i -c "export PUBLIC_IP=\"52.90.92.33\" PIP_EXTRA_INDEX_URL=\"https://certainly.isnot.org/pip/\" PRIVATE_IP=\"172.31.55.135\" PUBLIC_HOSTNAME=\"ec2-52-90-92-33.compute-1.amazonaws.com\" OS_TYPE=\"centos\" BOULDER_URL=\"http://172.31.50.127:4000/directory\" && ./test_leauto_upgrades.sh "

Aborting.
[localhost] local: rm le.tar.gz
0 ubuntu15.10 pass
1 ubuntu15.04LTS pass
2 ubuntu14.04LTS pass
3 ubuntu14.04LTS_32bit pass
4 ubuntu12.04LTS pass
5 debian8.1 pass
6 debian7.8.aws.1 pass
7 debian7.8.aws.1_32bit pass
8 amazonlinux-2015.09.1 fail
9 amazonlinux-2015.03.1 fail
10 RHEL7 pass
11 fedora23 pass
12 centos7 pass
13 centos6 pass
Terminating EC2 Instances and Cleaning Dangling EBS Volumes
Disconnecting from ubuntu@52.90.75.208... done.
```

**Comment by pde** [comment]
Test farm tests passed after the merge from master:
```
python multitester.py targets.yaml $KEY $USER scripts/test_leauto_upgrades.sh  --branch py26
/usr/lib/python2.7/dist-packages/cffi/model.py:526: UserWarning: 'point_conversion_form_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
Making local dir for test repo and logs: letest-1450289692
[localhost] local: mkdir letest-1450289692
Making local git repo
Testing branch py26 of https://github.com/letsencrypt/letsencrypt.git
[localhost] local: if [ -d letsencrypt ]; then rm -rf letsencrypt; fi
[localhost] local: git clone https://github.com/letsencrypt/letsencrypt.git --branch py26 --single-branch
Cloning into 'letsencrypt'...
remote: Counting objects: 24355, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 24355 (delta 13), reused 6 (delta 4), pack-reused 24321
Receiving objects: 100% (24355/24355), 6.56 MiB | 3.20 MiB/s, done.
Resolving deltas: 100% (17119/17119), done.
Checking connectivity... done.
[localhost] local: tar czf le.tar.gz letsencrypt
Testing against these images: [14 total]
ami-26d5af4c ubuntu15.10
ami-d92e6bb3 ubuntu15.04LTS
ami-7b89cc11 ubuntu14.04LTS
ami-9295d0f8 ubuntu14.04LTS_32bit
ami-0611546c ubuntu12.04LTS
ami-116d857a debian8.1
ami-e0efab88 debian7.8.aws.1
ami-e6eeaa8e debian7.8.aws.1_32bit
ami-60b6c60a amazonlinux-2015.09.1
ami-0d4cfd66 amazonlinux-2015.03.1
ami-a8d369c0 RHEL7
ami-518bfb3b fedora23
ami-61bbf104 centos7
ami-57cd8732 centos6
Connecting to EC2 using
 profile pde
 keyname pde-amazon2
 keyfile /home/pde/.ssh/pde-amazon2.pem
Making Security Group
  letsencrypt_test already exists
Requesting Instances...
Waiting on Boulder Server
 server ec2.Instance(id='i-5477aee5')
Configuring and Launching Boulder
Boulder Server at (SSH): ubuntu@54.172.114.103
[ubuntu@54.172.114.103] put: scripts/boulder_config.sh -> /home/ubuntu/boulder_config.sh
[ubuntu@54.172.114.103] run: ./boulder_config.sh 
[ubuntu@54.172.114.103] out: ++ curl -s http://169.254.169.254/2014-11-05/meta-data/public-hostname
[ubuntu@54.172.114.103] out: + public_host=ec2-54-172-114-103.compute-1.amazonaws.com
[ubuntu@54.172.114.103] out: ++ curl -s http://169.254.169.254/2014-11-05/meta-data/public-ipv4
[ubuntu@54.172.114.103] out: + public_ip=54.172.114.103
[ubuntu@54.172.114.103] out: ++ curl -s http://169.254.169.254/2014-11-05/meta-data/local-ipv4
[ubuntu@54.172.114.103] out: + private_ip=172.31.62.187
[ubuntu@54.172.114.103] out: ++ grep nameserver /etc/resolv.conf
[ubuntu@54.172.114.103] out: ++ cut '-d ' -f2
[ubuntu@54.172.114.103] out: ++ head -1
[ubuntu@54.172.114.103] out: + resolver_ip=172.31.0.2
[ubuntu@54.172.114.103] out: + resolver=172.31.0.2:53
[ubuntu@54.172.114.103] out: + cd /home/ubuntu/gocode/src/github.com/letsencrypt/boulder
[ubuntu@54.172.114.103] out: + sed -i '/listenAddress/ s/127.0.0.1:4000/172.31.62.187:4000/' ./test/boulder-config.json
[ubuntu@54.172.114.103] out: + sed -i '/baseURL/ s/127.0.0.1:4000/172.31.62.187:4000/' ./test/boulder-config.json
[ubuntu@54.172.114.103] out: + sed -i '/httpPort/ s/5002/80/' ./test/boulder-config.json
[ubuntu@54.172.114.103] out: + sed -i '/httpsPort/ s/5001/443/' ./test/boulder-config.json
[ubuntu@54.172.114.103] out: + sed -i '/tlsPort/ s/5001/443/' ./test/boulder-config.json
[ubuntu@54.172.114.103] out: + sed -i '/dnsResolver/ s/127.0.0.1:8053/172.31.0.2:53/' ./test/boulder-config.json
[ubuntu@54.172.114.103] out: 

[ubuntu@54.172.114.103] run: go run cmd/rabbitmq-setup/main.go -server amqp://localhost
[ubuntu@54.172.114.103] run: nohup ./start.py >& /dev/null < /dev/null &
[ubuntu@54.172.114.103] out: [1] 2413
[ubuntu@54.172.114.103] out: 

...................Boulder Server at (public ip): http://54.172.114.103:4000/directory
Boulder Server at (EC2 private ip): http://172.31.62.187:4000/directory
Uploading and running test script in parallel: scripts/test_leauto_upgrades.sh
Output routed to log files in letest-1450289692
[localhost] local: rm le.tar.gz
0 ubuntu15.10 pass
1 ubuntu15.04LTS pass
2 ubuntu14.04LTS pass
3 ubuntu14.04LTS_32bit pass
4 ubuntu12.04LTS pass
5 debian8.1 pass
6 debian7.8.aws.1 pass
7 debian7.8.aws.1_32bit pass
8 amazonlinux-2015.09.1 pass
9 amazonlinux-2015.03.1 pass
10 RHEL7 pass
11 fedora23 pass
12 centos7 pass
13 centos6 pass
Terminating EC2 Instances and Cleaning Dangling EBS Volumes
```

**Comment by pde** [comment]
@mgedmin handing this back to you to address Kuba's comment.

**Comment by bmw** [comment]
@pde, @kuba's comment was about the changes I made to the bootstrap scripts and I already addressed it here: eca5e7ae27928a8f2232ca9efb99e095120ab01b

**Comment by pde** [comment]
OK, merging.

**Pull request merged**
