### PR TITLE
Fix docker run command in using.rst

### PR DESCRIPTION
**Pull request by gionn**

### CODE REVIEW

**Comment by kuba** [comment]
LGTM

That's another regression introduced by #980

**Comment by pde** [comment]
Someone (@bmw ?) seemed pretty sure that the `run` verb wouldn't work inside docker because it wouldn't be able to see and reconfigure systemwide webservers.

**Comment by kuba** [comment]
You are mistaking "run" (earlier in the command) passed to Docker, with "run" (later in the command) passed to our binary. Configuration that doesn't work because it doesn't make sense for client to configure webserver inside Docker: (run, run). Configuration that doesn't work because i'ts not a valid Docker command: (auth, *).

**Comment by kuba** [comment]
@pde, btw should you wait for a review before merging, this wouldn't be a problem!

**Comment by bmw** [comment]
LGTM. Thanks @gionn!

**Pull request merged**
