### PR TITLE
Fix version command

### PR DESCRIPTION
**Pull request by Bachmann1234**
```
 bachmann@Matts-MacBook-Pro-2  ~/Code/letsencrypt   fix-version  letsencrypt --version
letsencrypt 0.1
```

Attempting issue https://github.com/letsencrypt/letsencrypt/issues/845

### CODE REVIEW

**Comment by pde** [comment]
Hi @Bachmann1234 ... I think that PR #863 already fixed this issue in master AFAICT.  Please reopen if that's not the case in your observation!

**Comment by Bachmann1234** [comment]
@pde ah! Cool.

**Comment by kuba** [comment]
Verified here as well. 1808b6fb948cae7bb880916747ac322da21cfef7 works fine with `--version`.

**Comment by Bachmann1234** [comment]
Yeah, think my timing was a smidge off. Sorry for the trouble

**Pull request closed without merging**
