### PR TITLE
Root prompt explanation + minor typos

### PR DESCRIPTION
**Pull request by philpraxis**
Minor modification to letsencrypt-auto to explain why the sudo and fix minor typo.

### CODE REVIEW

**Comment by philpraxis** [comment]
It seems the Travis CI fails are anyway happening regardless of this PR changes. 

Can anyone confirm?

I'm happy to update to newest commit that would fixe these Travis-CI failing errors from upstream as soon as it exists, reapply the patch and propose this PR again. Or you can merge direct. Just let me know.

**Comment by bmw** [comment]
Looks like a Travis heisenbug. Reran tests and everything passed.

**Comment by philpraxis** [comment]
Ok great. Then nothing to add to this, merge if needed.

**Comment by bmw** [comment]
LGTM. Waiting for a +1 for another dev before merging though as this will affect our users immediately.

**Comment by philpraxis** [comment]
Fantastic :)

**Comment by SwartzCr** [comment]
This looks fine to me, as it doesn't seem to change code. @bmw, feel free to merge

**Comment by bmw** [comment]
Merging. Thanks for the PR @philpraxis and sorry again about the Travis trouble.

**Comment by philpraxis** [comment]
Glad to help!

**Pull request merged**
