### PR TITLE
Merge augeas lens fix for backslashes at the start of regexps

### PR DESCRIPTION
**Pull request by pde**
From: hercules-team/augeas#325
Fixes: #1531

### CODE REVIEW

**Comment by domcleal** [comment]
There's a further bug report at https://github.com/letsencrypt/letsencrypt/issues/1294#issuecomment-161805063 which I've fixed in https://github.com/hercules-team/augeas/commit/ba10b23e3561f7fbac224fe0d1b21d5047192f7b.  Not sure if you want to bring that fix into this PR or file another?

**Comment by pde** [comment]
@domcleal @jdkasten it seems that your lens patch breaks our tests because we declare that [this file](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/tests/testdata/debian_apache_2_4/two_vhost_80/apache2/conf-available/bad_conf_file.conf) should error out.  In a quick test, Apache seems to run with that file, but won't server things from it even if I add a DocumentRoot?  That's kind of weird behaviour.  Do others get the same result?

**Comment by pde** [comment]
In retrospect, wish I'd made another PR rather making two lense changes in this one.  In fact, I'm going to do that...

**Comment by domcleal** [comment]
Yep, sorry for the confusion.

:+1: to this PR.

**Pull request merged**
