### PR TITLE
bootstrap: use a proper dependency test for Arch

### PR DESCRIPTION
**Pull request by grawity**
`pacman -T` exists for this exact purpose; it respects provides without having to manually code them into the script.

### CODE REVIEW

**Comment by pde** [comment]
1. If I understand it correctly, the previous code would install the latest version of each dependency; the new version will only install things that are completely missing. Though each approach can cause problems, I think it's probably safer to upgrade dependencies to their latest version.

2. @pritambaral are you okay with this change to the way gcc is handled? Superficially it looks like it could break your previous change, unless `gcc` is some kind of virtual package provided by `gcc-multilib`

**Comment by pde** [comment]
@MartijnBraam any thoughts?

**Comment by grawity** [comment]
`gcc` is a real package, but the 'provides' metadata of `gcc-multilib` lets it satisfy the `gcc` dependency.

Regarding updates – overall, in Arch, selective upgrades are not supported at all (since most packages don't have versioned dependencies), so IMHO both approaches can be equally risky (to overall system health).

IMHO, using `-T` is more flexible, since it allows other kinds of "alternative" packages, e.g. libressl providing openssl, or whiptail (libnewt) providing dialog.

**Comment by pritambaral** [comment]
@pde Yes, this seems like a better option. `gcc-multilib` provides `gcc`

@grawity Thanks for enlightening me about pacman's `-T` option

**Comment by bmw** [comment]
LGTM. Thanks for the PR @grawity.

**Comment by MartijnBraam** [comment]
@grawity The `-T` option is great! never knew about it. now I have to rewrite some scripts.

**Pull request merged**
