### PR TITLE
crypto_util: Remove cruft

### PR DESCRIPTION
**Pull request by ArchimedesPi**
Removed:
* `pyopenssl_x509_name_as_text(...)`
* `asn1_generalizedtime_to_dt(...)`

### CODE REVIEW

**Comment by kuba** [comment]
Yeah, any dead code can be removed.

**Comment by ArchimedesPi** [comment]
Weird, that shouldn't have failed. Nothing referenced that and it's the lint task that's failing.

**Comment by kuba** [comment]
`W:  7, 0: Unused import datetime (unused-import)`, https://travis-ci.org/letsencrypt/letsencrypt/jobs/83569361#L1005

**Comment by ArchimedesPi** [comment]
Woah, that's pretty aggressive that a single unused import fails the build! Fixed.

**Comment by kuba** [comment]
884d8e9 LGTM

Feel free to remove the rest, before mergers wake up ;)

**Comment by ArchimedesPi** [comment]
There's no more dead code in there afaik.

**Comment by kuba** [comment]
https://travis-ci.org/letsencrypt/letsencrypt/jobs/83570371#L550 suggest that the following lines are dead: 205-211, 221, i.e. `_pyopenssl_load` and `pyopenssl_load_certificate` could be removed.

**Comment by ArchimedesPi** [comment]
`_pyopenssl_load` is used by `pyopenssl_load_certificate` which is used [here in `cli.py`](https://github.com/letsencrypt/letsencrypt/blob/393f4b4997d4df45e0b433d1ab2075d7a8954c0d/letsencrypt/cli.py#L411).

**Comment by kuba** [comment]
@ArchimedesPi, ah, thanks for tracing this down. I guess we need a separate issue/PR to fix the coverage and write more unittests for `crypto_util` then. Are you up for that? :)

**Comment by ArchimedesPi** [comment]
Yep. This one can be merged, I've already prepared another one covering `_pyopenssl_load` and a couple other things.

**Comment by kuba** [comment]
Yeah, LGTM. You may want to remove "[WIP]" from the PR title.

**Comment by ArchimedesPi** [comment]
Done.

**Comment by bmw** [comment]
LGTM. Thanks for the PR @ArchimedesPi!

**Comment by ArchimedesPi** [comment]
Happy to help out :)

**Pull request merged**
