### PR TITLE
Use `localhost` when testing

### LINKED ISSUE #684: Allow specification of DNS server to use for simple_verify
Currently to run the boulder <-> client integration tests you need to add a `127.0.0.1 le.wtf` entry to your hosts file. It would make life a lot easier if a flag could be used to either set the DNS server to use, so we can use Boulders `dns-test-srv`, or a flag that specifies test mode and always queries localhost instead of the actual domain for the challenge verification code.

### PR DESCRIPTION
**Pull request by bmw**
Fixes #684.

### CODE REVIEW

**Comment by jmhodges** [comment]
Commented on letsencrypt/boulder#626:

Ick, I'd much prefer we get the dns test server we boot to know this host instead of adding yet another test mode boolean that will hide real code that really needs to work well. Removing the similar TestModes in boulder is on my Must Do list.

We kept hiding more code behind them as time marched on and now I'm very nervous about that code actually working well in production.

**Comment by bmw** [comment]
My response from letsencrypt/boulder#626:

The problem is we have competing goals here. The purpose of these two PRs was to close letsencrypt/letsencrypt#684 which asks for the ability to set a custom DNS server or have the client use `localhost` for testing. This is special test functionality which wouldn't be used in production. If we want to reduce all test code, we should continue to set up a custom host in `/etc/hosts` for testing as we did before.

Removing the testing boolean that I modified in the client is a bad idea in my opinion though. The code it is testing presents the user with a bash script they can run on their server to complete DV. The testing flag removes all user interaction (two lines of code) and executes the script instead of printing it. This allows us to actually make sure the script works as expected and it is the only case where we are doing integration tests with `SimpleHTTP`.

**Comment by kuba** [comment]
I think I agree with @jmhodges. I would keep the things as they are or alternatively amend `/etc/resolv.conf` to use Boulder's test DNS server. What is missing is the documentation about that "feature".

While I wouldn't say it makes a life *a lot* easier (re @rolandshoemaker in #684), it would make a life *slightly* easier... but who tests on their client machine anyway? Nowadays, integration testing requires you to set up: RabbitMQ, Go 1.5 (not available from the repos) and MySQL/MariaDB... so I personally leave all integration testing to Travis (or I test manually against staging env). And for Travis it's not hard to update `/etc/hosts`.

**Comment by bmw** [comment]
@kuba, I test on my client machine. With that said, after setting up RabbitMQ, Go, and MariaDB, adding an entry to `/etc/hosts` isn't a big deal for me. I'll close this PR and #684 for now.

**Pull request closed without merging**
