### PR TITLE
fedora is now using dnf as default package manager

### PR DESCRIPTION
**Pull request by gabx**
use dnf instead of yum

### CODE REVIEW

**Comment by kuba** [comment]
Thanks for you interest in the project.

As the inline comments and name (`_rpm_common.sh`) suggest this script is meant to work with generic RPM-based distros, including CentOS. AFAIK Fedora's `yum` internally calls `dnf` for backwards compatibility. If it's really required to use `dnf`, then we need some `switch/case` block.

**Comment by PatrickHeppler** [comment]
I wrote a switch, see #673

**Comment by kuba** [comment]
Please close it in favor of #747.

**Comment by jdkasten** [comment]
This has been pulled in via #747

**Pull request closed without merging**
