### PR TITLE
Revert "Revert PR #708."

### PR DESCRIPTION
**Pull request by kuba**
#721 was not a real fix - tests pass on our side, so problem is to be found somewhere else...

### CODE REVIEW

**Comment by jmhodges** [comment]
This can't be done until it's figured out why this worked in letsencrypt but not boulder

As boulder's config is mostly cargo-culting letsencrypt's code to set up the python env, we'll need some help from y'all, the python experts, to figure that out.

**Comment by kuba** [comment]
Yeah, sorry, should've mentioned it's not ready to be pulled. I just wanted
to have some way of tracking this issue.

**Comment by jdkasten** [comment]
I am not sure we want this.  If we are going to continue supporting 2.6 (@kuba's request) we will need our test cases to work in both 2.6 and 2.7.  Allowing Mock versions greater than 1.1 will allow us to introduce new mock features into the tests while developing with 2.7, which will break 2.6 when we send it to Travis.

It also adds additional complexity to our integration tests.which consistently break on their own.

**Comment by kuba** [comment]
We want this to make sure packaging is easy, e.g.
https://github.com/letsencrypt/letsencrypt/pull/701#discussion_r37695857.

**Comment by kuba** [comment]
The problem has been chased down to be an upstream incompatibility with older versions of `pip`, c.f. https://github.com/testing-cabal/mock/issues/316.

@jmhodges, can I please ask you to add `pip install -U setuptools pip` before `pip install -e acme ...` in Boulder (as per instructions in https://github.com/letsencrypt/letsencrypt/pull/722/files#diff-5f059e53687997d121c03d63d11f103bR129)? I've tested it to work with this PR.

This is now clear to merge. @bmw?

cc: @hlieberman, it closes #779, i.e. incompatibilities with mock 1.3.

**Comment by kuba** [comment]
Merged with `master`.

**Comment by kuba** [comment]
Clear to merge, Boulder will be fixed in https://github.com/letsencrypt/boulder/pull/922.

**Comment by bmw** [comment]
LGTM. Thanks for tracking the problem down @kuba.

**Pull request merged**
