### PR TITLE
don't iDisplay if logging

### PR DESCRIPTION
**Pull request by SwartzCr**
add a flag variable to view_config_changes which returns the changes as a string if we're logging it.
I'm unsure how to test since the comments left in https://github.com/letsencrypt/letsencrypt/pull/2009 don't specify where this issue was arising

### CODE REVIEW

**Comment by SwartzCr** [comment]
to fix #2002

**Comment by joohoi** [comment]
TBH, I'd simplify it all by just logging.debug:ing the changes every time in view_config_changes().

**Comment by SwartzCr** [comment]
so you mean, log then iDisplay? Will that get called when tls_sni_01.py gets called?

**Comment by joohoi** [comment]
Ah, you are right. Sorry, was reviewing in a hurry. 

LGTM

**Comment by pde** [comment]
Hrm, spotted after merging:

It's a little bit dangerous to have the `for_logging` argument on one implementation of `view_config_changes`, but not in the [interface it's part of](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/interfaces.py#L333) and all the other implementations.  Currently it's only safely usable if the call site knows for sure it's calling this method on the apache plugin, and not a different plugin.

So we should ask ourselves, "is this the semantics we want from the interface?" If so, add it to the interface and also implement it in the other plugins.  Prrrobably it's safe to leave this merged and just open a ticket to make that decision.

**Pull request merged**
