### PR TITLE
Make the new letsencrypt-auto script the main one. [requires minor revision]

### PR DESCRIPTION
**Pull request by erikrose**
Remove the old bootstrap scripts, which have been subsumed into letsencrypt-auto-source/pieces/bootstrappers. They no longer need to be dispatched among manually: everyone can just run letsencrypt-auto --os-packages-only, regardless of OS.

Make the root-level le-auto a symlink to the canonical version. It should thus still work for people running le-auto from a git checkout.

### CODE REVIEW

**Comment by erikrose** [comment]
Now that there's nothing left in the bootstrap folder, we should move the remaining couple of venv scripts somewhere. Any ideas? `tools/venv`?

**Comment by pde** [comment]
Yeah, or just `tools/`.  Can you also grep the `docs/` for references to these things in their current locations, and update accordingly?

**Comment by erikrose** [comment]
Yep, I already grepped the docs for "bootstrap", of course. I'll move the venv stuff and update the docs for those as well.

**Comment by erikrose** [comment]
@pde Done.

**Comment by pde** [comment]
Merging!

**Pull request merged**
