### PR TITLE
Leap days are fun

### PR DESCRIPTION
**Pull request by bmw**

### CODE REVIEW

**Comment by bmw** [comment]
fixes #2564 and brings in #2565

**Comment by bmw** [comment]
@jsha: [log](https://gist.github.com/b8e6432fd960bc304413) of spurious boulder problem.

**Comment by schoen** [comment]
Thanks for the fix!

**Comment by jsha** [comment]
Thanks for the log! This is exactly what I was hoping to see: mysql logging timeouts.

**Pull request merged**
