### PR TITLE
letsencrypt_dns

### PR DESCRIPTION
**Pull request by kuba**
Supersedes #291.

### CODE REVIEW

**Comment by kuba** [comment]
@rolandshoemaker, would you be able to test it, please? :)

**Comment by bkleef** [comment]
@kuba we are really looking forward to use this feature as it's impossible to use a webserver in our situation. Can we test this branch, is the Let's Encrypt CA ready for this?
Even better could it be merged in master?

**Comment by jdkasten** [comment]
We aren't quite yet acme-spec v04 compliant and I am not sure if Boulder is issuing the latest DNS challenges.

**Comment by jdkasten** [comment]
Yes, it would be great to get it merged into master once it is able/has been tested.

**Comment by rolandshoemaker** [comment]
I'll try to pull myself away from Boulder sometime this week to test this
out locally.

**Comment by kuba** [comment]
Further development is blocked on https://github.com/letsencrypt/boulder/issues/753.

**Comment by kuba** [comment]
This has been OBE for long time now, closing!

**Pull request closed without merging**
