### PR TITLE
Verify both symlink and target

### LINKED ISSUE #2054: OSError: [Errno 22] Invalid argument
hi,

my renewal does not work. I'm running Ubuntu 14.04 with python 2.7.6 on my machine. My config file in `/etc/letsencrypt/cli.ini` looks as follows (I changed the domain names):

```
rsa-key-size = 4096
server = https://acme-staging.api.letsencrypt.org/directory
email = mail@mydomain.com
domains = mydomain.com
text = True
authenticator = webroot
webroot-path = /var/www/html
agree-tos = True
renew-by-default = True
```

If I now run (as root) the command `/opt/letsencrypt/letsencrypt-auto certonly --config /etc/letsencrypt/cli.ini` I get the following error:
```
Updating letsencrypt and virtual environment dependencies......
Requesting root privileges to run with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt certonly -a webroot --config /etc/letsencrypt/cli.ini
An unexpected error occurred:
OSError: [Errno 22] Invalid argument: '/etc/letsencrypt/live/mydomain.com/cert.pem'
Please see the logfiles in /var/log/letsencrypt for more details.
```

**/var/log/letsencrypt/letsencrypt.log**
```
2016-01-01 18:28:39,820:DEBUG:letsencrypt.cli:Root logging level set at 30
2016-01-01 18:28:39,820:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-01-01 18:28:39,820:DEBUG:letsencrypt.cli:letsencrypt version: 0.1.1
2016-01-01 18:28:39,820:DEBUG:letsencrypt.cli:Arguments: ['-a', 'webroot']
2016-01-01 18:28:39,820:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-01-01 18:28:39,821:DEBUG:letsencrypt.cli:Requested authenticator webroot and installer None
2016-01-01 18:28:39,823:DEBUG:letsencrypt.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/.well-known/acme-challenge
2016-01-01 18:28:39,823:DEBUG:letsencrypt.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/.well-known/acme-challenge
2016-01-01 18:28:39,823:DEBUG:letsencrypt.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/.well-known/acme-challenge
2016-01-01 18:28:39,823:DEBUG:letsencrypt.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/.well-known/acme-challenge
2016-01-01 18:28:39,824:DEBUG:letsencrypt.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/.well-known/acme-challenge
2016-01-01 18:28:39,824:DEBUG:letsencrypt.display.ops:Single candidate plugin: * webroot
Description: Webroot Authenticator
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = letsencrypt.plugins.webroot:Authenticator
Initialized: <letsencrypt.plugins.webroot.Authenticator object at 0x7f67d00d9450>
Prep: True
2016-01-01 18:28:39,824:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.webroot.Authenticator object at 0x7f67d00d9450> and installer None
2016-01-01 18:28:39,839:DEBUG:letsencrypt.cli:Picked account: <Account(xxxxxxxxxxxxxxxxxxxxxxxx)>
2016-01-01 18:28:39,839:DEBUG:root:Sending GET request to https://acme-staging.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-01-01 18:28:39,842:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-01-01 18:28:40,390:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 279
2016-01-01 18:28:40,392:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '279', 'Expires': 'Fri, 01 Jan 2016 18:28:41 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 01 Jan 2016 18:28:41 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'QSF70cRfDBqwuL0GJphAiU-cdxGUlyB1Z-gIjJH3x4A'}. Content: '{"new-authz":"https://acme-staging.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-staging.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-staging.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-staging.api.letsencrypt.org/acme/revoke-cert"}'
2016-01-01 18:28:40,393:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '279', 'Expires': 'Fri, 01 Jan 2016 18:28:41 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 01 Jan 2016 18:28:41 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'QSF70cRfDBqwuL0GJphAiU-cdxGUlyB1Z-gIjJH3x4A'}): '{"new-authz":"https://acme-staging.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-staging.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-staging.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-staging.api.letsencrypt.org/acme/revoke-cert"}'
2016-01-01 18:28:40,394:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1396, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 598, in obtain_cert
    _auth_from_domains(le_client, config, domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 379, in _auth_from_domains
    action, lineage = _treat_as_renewal(config, domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 235, in _treat_as_renewal
    ident_names_cert, subset_names_cert = _find_duplicative_certs(config, domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 204, in _find_duplicative_certs
    candidate_names = set(candidate_lineage.names())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/storage.py", line 456, in names
    target = self.current_target("cert")
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/storage.py", line 273, in current_target
    target = os.readlink(link)
OSError: [Errno 22] Invalid argument: '/etc/letsencrypt/live/mydomain.com/cert.pem'
```

Do you know how I can solve this problem?

Regards,
Jan Bücker

### PR DESCRIPTION
**Pull request by bmw**
fixes #2054 and supersedes #2088

### CODE REVIEW

**Comment by schoen** [comment]
LGTM. I agree that this is clearer and safer than the original version.

One question: I spent a bunch of time of time working on logic to allow reuse of private keys by making `privkey.pem` be a symlink to (if I remember correctly) a symlink to a previous key. If I've remembered that right, I think that code is currently unreachable from any of our existing verbs (there is no way to ask the client to reuse the privkey at renewal). But if it were used, would this code regard a lineage that used it as valid?

**Comment by schoen** [comment]
(I'm referring to https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/storage.py#L785)

**Comment by bmw** [comment]
Looking at this, the only place that now uses an absolute path that may have used a relative one before is in `_consistent`, which is never called and looking at https://github.com/letsencrypt/letsencrypt/pull/2454/files#diff-ff3d5a32d585a6527a2fcd1bebb3e1c7L231, this change shouldn't affect the function's behaviour if it's used in the future.

**Comment by pde** [comment]
Also LGTM, merge when ready.

**Comment by schoen** [comment]
I will file a separate issue about cautions when using the `privkey=None` feature in `RenewableCert` in the future.

**Comment by schoen** [comment]
Arguably #407 and #1491 already sort of cover that. I commented in #1491 about this.

**Pull request merged**
