### PR TITLE
Merge master into debian

### PR DESCRIPTION
**Pull request by fmarier**
No changes at all, just a merge from master.

### CODE REVIEW

**Comment by hlieberman** [comment]
I think we may be duplicating work, @fmarier.  This branch isn't currently safe to merge until python-cryptography 1.0.1-4 merge in and close Debian bug 799628.  I also reverted the changes to the manual tests, instead of skipping it, until the upstream mock bug is fixed.

How can we better coordinate on this, @fmarier?  I've been doing remerges into hlieberman/letsencrypt's debian branch every couple of days.  I can do it in your repository instead, if you prefer that and give me the necessary access.

**Comment by fmarier** [comment]
> How can we better coordinate on this, @fmarier? I've been doing remerges into my fork every couple of days. I can do it in your repository instead, if you prefer that and give me the necessary access.

That's part of why I suggested [regular release tags](https://groups.google.com/a/letsencrypt.org/d/topic/client-dev/0V28aBmEnrg/discussion). Once we get releases, we'll all be developing against the same upstream version and focusing on pushing changes upstream in between releases.

In the meantime, would you like to submit a PR onto `fmarier/letsencrypt` with your other changes so that I can ensure everything gets merged as part of #795?

**Comment by fmarier** [comment]
BTW, this is ready to merge. I'll follow up on the other PR.

**Comment by jdkasten** [comment]
Thanks, @fmarier.

**Pull request merged**
