### PR TITLE
Add bootstrap for openSUSE based OS...

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by mimi1vx** [comment]
checks are failing for travis internal/setup ... not for PR

**Comment by pde** [comment]
Retrying travis. @mimi1vx if you'd like us to merge this before the Public Beta launch, could you do the following:
1. Let us know that you're willing to play a support role for users who file bugs about installation on these platforms
2. Update the PR to use ExperimentalBootstrap (which was [added here](https://github.com/letsencrypt/letsencrypt/pull/1346/files) until you've gained confidence that it works on a wide range of SLE and OpenSUSE systems?

I've restarted the travis tests..

**Comment by mimi1vx** [comment]
@pde  ExperimentalBootstrap added , + support reduced to openSUSE, SLE doesn't have python-virtualenv package + tested on Tumbleweed + Leap 42.1

**Comment by pde** [comment]
Thanks!

**Pull request merged**
