### PR TITLE
Fixed typo in cipher suite list

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
I think they should also be separated by a ```:```

**Comment by pde** [comment]
Both of these ciphers seem to exist in the source, so it's a little unclear to me if this is actually a typo.  @ivanr ?

**Comment by ivanr** [comment]
It's not a typo; EDH-RSA-DES-CBC3-SHA is the correct name. More recent versions of OpenSSL will accept both variants, probably because most people expect the name to start with "DHE-". However, older versions of OpenSSL accept only the former.
```
$ openssl version
OpenSSL 0.9.8k 25 Mar 2009
$ openssl ciphers -v DHE-RSA-DES-CBC3-SHA
Error in cipher list
5325:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1217:
$ openssl ciphers -v EDH-RSA-DES-CBC3-SHA
EDH-RSA-DES-CBC3-SHA    SSLv3 Kx=DH       Au=RSA  Enc=3DES(168) Mac=SHA1
```
The "EDH-" variant is still the only variant listed in the "openssl ciphers" output:
```
$ openssl version
OpenSSL 1.0.2d 9 Jul 2015
$ openssl ciphers -V | grep EDH
          0x00,0x16 - EDH-RSA-DES-CBC3-SHA    SSLv3 Kx=DH       Au=RSA  Enc=3DES(168) Mac=SHA1
          0x00,0x13 - EDH-DSS-DES-CBC3-SHA    SSLv3 Kx=DH       Au=DSS  Enc=3DES(168) Mac=SHA1
          0x00,0x15 - EDH-RSA-DES-CBC-SHA     SSLv3 Kx=DH       Au=RSA  Enc=DES(56)   Mac=SHA1
          0x00,0x12 - EDH-DSS-DES-CBC-SHA     SSLv3 Kx=DH       Au=DSS  Enc=DES(56)   Mac=SHA1
```
Although it's common to separate cipher suites using colon, I prefer spaces, which make the configuration easier to read.

**Comment by J0WI** [comment]
Okay, thanks for the explanation!

**Pull request closed without merging**
