### PR TITLE
Docker option for production [needs revision]

### PR DESCRIPTION
**Pull request by goacid**
By default docker image point to stagging url. Add a command line for dokcer on production url.

### CODE REVIEW

**Comment by kuba** [comment]
Docker image uses defaults of the CLI client, which currently is the production API endpoint (see https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/constants.py#L19). To be explicit, you only need a custom `--server` if you want to use Docker and staging API endpoint. So this is the other way round as suggested by you and your PR.

**Comment by bmw** [comment]
You can also simply use `--staging` to use the staging URL.

**Comment by bmw** [comment]
@goacid, there have been review comments on this for a month now and we haven't heard back from you. I'm closing this PR. Feel free to open a new one if you'd like us to rereview. Thanks!

**Comment by goacid** [comment]
Hi
That is ok for me. I needed to update my image so that is was ok.

**Pull request closed without merging**
