### PR TITLE
acme: v4 DNS challenge

### PR DESCRIPTION
**Pull request by kuba**

### CODE REVIEW

**Comment by bmw** [comment]
LGTM! Thanks @kuba.

**Comment by ezeeetm** [comment]
@TheBigBear you ever get an answer here?  If this PR got merged, then many of us would love to start using it.

**Comment by TheBigBear** [comment]
@ezeeetm no, I never heard back on this. sorry.

**Comment by pde** [comment]
@TheBigBear @ezeeetm it'll need a patch to thread it into the manual authenticator plugin.  Send us a pull request if you want it to happen faster ;)

**Comment by TheBigBear** [comment]
@pde ok, you talking of it needing additions in 'https://github.com/letsencrypt/letsencrypt/letsencrypt/plugins/manual.py' , to get it useable? or will/should it get it's own 'dns' plugin, something like 'https://github.com/letsencrypt/letsencrypt/letsencrypt/plugins/dns.py'?

**Comment by bmw** [comment]
@TheBigBear, the code added to `challenges.py` basically just adds data structures and utility functions that can be used to complete the challenge. A [plugin](https://letsencrypt.readthedocs.org/en/latest/using.html#plugins) has to be written/modified to actually solve this challenge.

Also, [boulder](https://github.com/letsencrypt/boulder) the server side of Let's Encrypt does not yet have a finished implementation of this challenge.

**Comment by kuba** [comment]
DNS v4 challenge is different than `dns-01` challenge. I'm currently working to update `challenges.py` (see #1826) to support that latest challenge. I will not work on a plugin, so feel free to grab the plugin task itself, but it might be hard to start working on that until `challenges.py` is updated.

**Pull request merged**
