### PR TITLE
add authors/copyright, include it in docs, setup.py fixed - fixes #211 and #214

### LINKED ISSUE #211: add AUTHORS, CONTRIBUTORS or CREDITS to toplevel dir
it's useful so people know who worked on the software.
also it can be referred to in (c) notices (if appropriate).

.rst maybe?

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
list is generated from git repo log, I removed duplicate persons / technical accounts manually.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
updated with the #214 fix, based on the previous changes in this PR.

**Comment by ThomasWaldmann** [comment]
Note: "The Let's Encrypt Team" maybe needs discussion. The people in the AUTHORS.rst list are just the people working on the client repo, so it maybe should be "The Let's Encrypt Client Team"?

**Comment by jdkasten** [comment]
Sorry for sitting on this.  This is a higher order bit that needs to be taken care of/decided by the organizations involved.  I have alerted people of the issue who should be involved in such a decision.  (This repo has actually been around for a couple of years with a few different implementations of protocols and use-cases.)

I am trying to just focus on getting working code in the repo.  Hopefully we will get an answer soon.

**Comment by pde** [comment]
Copyright to most of the lets-encrypt-preview code is currently owned by EFF as a result of the [work for hire](https://en.wikipedia.org/wiki/Work_for_hire) doctrine.  So let's keep the LICENSE file clear and simple on that, and then credit contributors separately.

**Comment by ThomasWaldmann** [comment]
Well, IANAL, but AFAIK it works like this: someone has/claims copyright and then gives a license.

The claim is currently missing, so licensing is missing the base somehow.

Also, the work for hire is only applying to code written by people EFF hired, which might apply for most, but not all code.

**Pull request closed without merging**
