### PR TITLE
Be doubly sure to install python2.7-dev

### PR DESCRIPTION
**Pull request by pde**
Probably solves #1564, whether or not it's a real issue!

### CODE REVIEW

**Comment by bmw** [comment]
So I'm not convinced this shouldn't go in, but I'm not convinced it should either. The downsides I see with this are:

1. Increases code complexity with little/no gain. We cannot reproduce the problem and we've had only one report of the issue with 35k+ PyPI downloads in the past month.
2. Shuns Python 2.6 support. We've put a non-trivial amount of effort into keeping this project working on Python 2.6. Should we prefer Python 2.7 so strongly as to explicitly install Python 2.7 packages? I think the answer is no.
3. Duplicates the role of a package manager. We need `python-dev`. The user's package manager should be able to determine whether `python2.6-dev` or `python2.7-dev` should be installed. We should avoid building a mini-package manager into Let's Encrypt.

Thoughts?

**Comment by pde** [comment]
Those seem like reasonable concerns.  Re: forcing py27, we do [agressively prefer py27](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-auto#L85) if it's present; it would probably be "most correct" to only try this if we are running with python2.7 or python27 as our executable.  But that's taking us even further in the direction of complexity.

**Comment by bmw** [comment]
We can (and probably should) prefer Python 2.7, but we shouldn't force people to use it.

Personally, I'd like to close this PR and not merge it in for now. If in the future, we continue to have reports about missing `python2.7-dev`, we can either reopen or add the installation of `python2.7-dev` to `letsencrypt-auto` which knows the version of Python you're running.

**Comment by pde** [comment]
SGTM.

**Pull request closed without merging**
