### PR TITLE
Real py26 support

### LINKED ISSUE #2087: Python 2.6 support
According to https://github.com/letsencrypt/letsencrypt, System Requirements:

"The Let's Encrypt Client presently only runs on Unix-ish OSes that include Python 2.6 or 2.7..."

However, when I run ./letsencrypt-auto --help, I get:

"WARNING: Python 2.6 support is very experimental at present...
if you would like to work on improving it, please ensure you have backups
and then run this script again with the --debug flag!"

My question is, when will Python 2.6 be fully supported?

thanks

### PR DESCRIPTION
**Pull request by bmw**
fixes #2087

### CODE REVIEW

**Comment by pde** [comment]
LGTM.  Needs another +1.

**Comment by pde** [comment]
(and needs test farm tests)

**Comment by pde** [comment]
```
time python multitester.py targets.yaml ~/.ssh/pde-amazon2.pem pde scripts/test_letsencrypt_auto_certonly_standalone.sh --branch real-py26-support 
...
0 ubuntu15.10 pass
1 ubuntu15.04LTS pass
2 ubuntu14.04LTS pass
3 ubuntu14.04LTS_32bit pass
4 ubuntu12.04LTS pass
5 debian8.1 pass
6 debian7.8.aws.1 pass
7 debian7.8.aws.1_32bit pass
8 amazonlinux-2015.09.1 pass
9 amazonlinux-2015.03.1 pass
10 RHEL7 pass
11 fedora23 pass
12 centos7 pass
13 centos6 fail
```

**Comment by pde** [comment]
The error was: 
```
[centos@54.152.181.138] out: Complete!
[centos@54.152.181.138] out: Creating virtual environment...
[centos@54.152.181.138] out: ./letsencrypt-auto: line 163: virtualenv: command not found
[centos@54.152.181.138] out: 

ami-57cd8732 - centos6 FAIL
```
This might be a regression, but I'm not sure...

**Comment by bmw** [comment]
That failure seems unrelated to this PR. I seem to be unable to run test farm tests and am getting:
```
botocore.exceptions.ClientError: An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-5f490b35]' does not exist
```
Can anyone run the test against master and see if they get the same CentOS6 failure?

**Comment by erikrose** [comment]
@pde's failure might be something along the lines of #2300.

**Comment by SwartzCr** [comment]
I ran with you branch and got:
0 ubuntu15.10 pass
1 ubuntu15.04LTS pass
2 ubuntu14.04LTS pass
3 ubuntu14.04LTS_32bit pass
4 ubuntu12.04LTS pass
5 debian8.1 pass
6 debian7.8.aws.1 pass
8 amazonlinux-2015.09.1 pass
9 amazonlinux-2015.03.1 pass
10 RHEL7 pass
11 fedora23 pass
12 centos7 pass
13 centos6 pass

**Comment by pde** [comment]
On master I see straight `pass`es.

**Comment by bmw** [comment]
@pde, my branch passed when @SwartzCr ran the tests.

**Comment by pde** [comment]
OK, I now got a pass too.  I'm not sure why...

**Comment by erikrose** [comment]
LGTM too! And since I landed the le_auto Travis stuff yesterday, the le-auto tests have run over this as well.

**Comment by durian808** [comment]
Where do I get files for fresh install, to try this out on my CentOS 6.6?  (I have old install that gave me the warning about Py26.)
Can I use this: https://community.letsencrypt.org/t/quick-start-guide/1631
Or "git pull" ??  Need a little help here... new to this.  Thanks.

**Comment by bmw** [comment]
@durian808, doing a `git pull` to get an updated copy of the repo should work.

**Pull request merged**
