### PR TITLE
Support Apache 2.2

### PR DESCRIPTION
**Pull request by SwartzCr**

### CODE REVIEW

**Comment by SwartzCr** [comment]
@pde fixed linting errors

**Comment by pde** [comment]
LGTM.  Will need another +1 for the bootstrap script changes.

**Comment by pde** [comment]
Fixes: #1208

**Comment by hlieberman** [comment]
I'd prefer to see two minor changes before we merge this.

1. I'd like us to either prompt the user to permit installing wheezy-backports, or to give them a couple of seconds after a warning to control-C.
2.  If we're going to automatically install wheezy-backports, it should be into /etc/apt/sources.list.d/wheezy-backports.list.  Makes it easier to remove.

Other than that, LGTM.

**Comment by pde** [comment]
I think making the user race to press control-c is a bit crazy.  How about we say 

```
installing libaugeas0 from wheezy backports....
(Backports are only installed if you explicitly request them with `apt-get install -t wheezy-backports`, but you can delete /etc/apt/sources.list.d/wheezy-backports.list if you want no further backports to be visible on your system)
```

**Comment by pde** [comment]
multitest scripts/test_leauto_upgrades.sh:

0 ubuntu15.10 pass
1 ubuntu15.04LTS pass
2 ubuntu14.04LTS pass
3 ubuntu14.04LTS_32bit pass
4 ubuntu12.04LTS pass
5 debian8.1 pass
6 debian7.8.aws.1 pass
7 debian7.8.aws.1_32bit pass
8 amazonlinux-2015.09.1 pass
9 amazonlinux-2015.03.1 pass
10 RHEL7 pass
11 fedora23 pass
12 centos7 pass
13 centos6 pass

**Comment by joohoi** [comment]
+1 LGTM, have fiddled around with the changes a lot and it's working alright.

**Comment by pde** [comment]
OK, game on!

**Comment by ehsaan** [comment]
did a fresh clone and still get that same error :( 
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Unable to parse runtime variables',)

is there a way I can get more useful information out of the logs?

**Comment by joohoi** [comment]
@brunosabot @ehsaan Are you running mod_define and defining variables in Apache configuration files? We're unable to currently parse the defines in Apache 2.2, and hence this will, and should error out at the current state.

**Comment by joohoi** [comment]
@brunosabot maybe we should open a new issue for this. Check your apache configuration files, and search for "Define" - statements to the issue ticket, I think I know what's going on in there.

**Comment by pde** [comment]
Yes @brunosabot and @ehsaan can you please post your configuration files in #2012?

**Pull request merged**
