### PR TITLE
Plesk Plugin (fixes #16)

### LINKED ISSUE #16: Support for Plesk
Hello,
I don't know if this is the right place for this kind of question, but will Plesk be supported?
As you say only `lets-encrypt example.com` is needed for generating and activating an SSL certificate for this domain I wonder if this works with Plesk's certificate management.
In Plesk you have to add a ca-certificate and your own certificate to a domain/subdomain to get it activated.

Kind regards,
Stefan

### PR DESCRIPTION
**Pull request by xgin**
Plesk support #16 - install certificate via Plesk API.
The problem of letsencrypt usage on a server with Plesk is that the last will overwrite web servers configurations on any changes.
Solution is do not write directly to the web server, but pass certificates to Plesk.

I am from Plesk team, but the plugin has been implemented in my free time.
Also in plans there is UI integration via Plesk SDK.

There are some TODOs.
Tests coverage is not sufficient.
Only local installation is supported now: the challenge should be reworked with FTP.
You can try it with docker image https://hub.docker.com/r/plesk/plesk/
Any feedback would be very appreciated.

### CODE REVIEW

**Comment by pde** [comment]
This is great @xgin !  We won't have many cycles to provide feedback until we've worked through the blaze of tickets for the public beta, but a few high level points:

- We're theoretically open to merging this into our tree if you or your colleagues are committed to maintaining it there
- It would also be fine for you to keep it in a forked repo, allowing you to do releases on a different schedule

Each of these has advantages and disadvantages.  Probably the second path is best for the time being, but in the long run either could work.

**Comment by pde** [comment]
A third option (which @kuba advocates strongly) is to package the plugin as a separate repo, like this one:

https://github.com/e00E/lets-encrypt-icecast

Distribution of the plugin would then operate by uploading to pypi / pip, and separate packaging by distributions.

**Comment by kuba** [comment]
@pde, note that distributions are already packaging everything separately, so it doesn't matter if it's in our tree or not.

**Comment by kuba** [comment]
@xgin, this looks like an awesome plugin and it's be great to have it at launch time :) Could you please ping me (Kuba) on IRC (#letsencrypt-dev)? I would like to help to get it packaged.

**Comment by xgin** [comment]
@kuba, yes I will soon. It is going to be helpful.

Does the community interest in packaging of the plugin on PyPI in a separate package (e.g. letsencrypt-plesk)?
Basic utility package (letsencrypt) is already able to use only available plugins - why don't you want to make it a swiss knife? That makes people know about server components installed, instead of easily 'apt-get install letsencrypt'.
Our goal is distributing within Plesk's extensions catalog (ext.plesk.com) - there are some problems here (with os-specific dependences) we are solving now.

About source code repo. Right now it is useful for me to keep this PR open for tracking conflicts and API changes. But in case the plugin is built as a separate package, we should likely create an own repo.

**Comment by kuba** [comment]
No matter how we approach the source code repo organisation, `letsencrypt-plesk` will be packaged separately (I have already reserved https://pypi.python.org/pypi/letsencrypt-plesk for that purpose). This is how it works even for the "official" plugins like `letsencrypt-apache` and `letsencrypt-nginx`. See https://github.com/letsencrypt/letsencrypt/wiki/Packaging#releases.

Nevertheless, I personally strongly encourage you, to create a separate repo with Plesk plugin only, just like https://github.com/e00E/lets-encrypt-icecast. I'm ready to help you set it up this way and prepare your plugin for releases.

Please join me on IRC to discuss more details.

**Comment by kuba** [comment]
After discussion with @xgin, I'm going to close this PR. The plugin will soon live at https://github.com/plesk/letsencrypt-plesk.

**Pull request closed without merging**
