### PR TITLE
pep8 love

### PR DESCRIPTION
**Pull request by kuba**
@hlieberman pointed out that we fail a lot of `pep8` checks - indeed `pep8` checks a bit different things than `pylint`. This PR adjusts `pylint` settings, fixes `pep8` warnings and sets up tox (and Travis) to run `pep8` over the entire code base. 

@hlieberman, could you please have a look? :)

### CODE REVIEW

**Comment by kuba** [comment]
re failed Travis: seems like (semi-anticipated) race condition in the py27 test - not something to be worried about in this PR.

**Comment by hlieberman** [comment]
LGTM!

**Comment by kuba** [comment]
Merged with master, disabled Travis failure triggering, PTAL, @jdkasten

**Comment by jdkasten** [comment]
Thanks!

**Pull request merged**
