### PR TITLE
fix apache 2.2

### PR DESCRIPTION
**Pull request by SwartzCr**
If we have to call parser.find_dir, save changes first
linked to #2228

### CODE REVIEW

**Comment by bmw** [comment]
Travis failures are due to Travis, not the PR.

So as I expressed in irc, temporary saves are meant to be reverted and there are number of places in the code where they are done so (such as when `letsencrypt` is run again). With this in mind, putting a temporary save in a lower level function like this makes me nervous. I can see other code calling `is_name_vhost` in the future, changes appear to be saved, but are then reverted when the client is run again.

To avoid this problem, what if we put the temporary save before this [line](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/tls_sni_01.py#L79) with a comment describing its purpose. In `perform`we know all the changes we're trying to make are temporary and the problem I described in the above paragraph won't occur.

Additionally, while it certainly doesn't have to go into this PR, it'd be nice if we could avoid this problem in the future by having affected functions like `parser.find_dir` check/assert if there are any unsaved changes. I'm not sure how hard this is, but it'd help avoid confusion for people in the future. Again, this doesn't have to go in this PR.

Regardless, I believe this surprisingly simple fix will work. Thanks for tracking down the problem @SwartzCr!

**Comment by SwartzCr** [comment]
@bmw good call, I've moved the save call to tls_sni_01 where you suggested (will need testfarm tests I suppose)
I've also opened an issue with python-augeas: https://github.com/hercules-team/python-augeas/issues/15
and an issue in LE for working around the match issue: #2265

**Comment by pde** [comment]
Test farm results:
```
letstest/letest-1453422306$ cat results 
0 ubuntu15.10 pass
1 ubuntu15.04LTS pass
2 ubuntu14.04LTS pass
3 ubuntu14.04LTS_32bit pass
4 ubuntu12.04LTS pass
5 debian8.1 pass
6 debian7.8.aws.1 pass
7 debian7.8.aws.1_32bit pass
8 amazonlinux-2015.09.1 fail
9 amazonlinux-2015.03.1 fail
10 RHEL7 pass
11 fedora23 pass
12 centos7 pass
13 centos6 fail
```

**Comment by pde** [comment]
So we just got Debian 7 and Ubuntu 12 Apache support...

**Comment by pde** [comment]
The CentOS 6 failure is interesting and may require mitigation to not create a broken experience for those users:

```
[centos@54.86.84.148] out: Successfully installed ConfigArgParse-0.10.0 Jinja2-2.8 MarkupSafe-0.23 PyOpenSSL-0.15.1 Pygments-2.1 Sphinx-1.3.4 acme alabaster-0.7.7 argparse-1.4.0 astroid-1.3.5 babel-2.2.0 backports.ssl-match-hostname-3.5.0.1 cffi-1.5.0 configobj-5.0.6 coverage-4.0.3 cryptography-1.2.1 docker-py-1.6.0 docutils-0.12 enum34-1.1.2 idna-2.0 ipaddress-1.0.16 letsencrypt letsencrypt-apache letsencrypt-compatibility-test letsencrypt-nginx letshelp-letsencrypt linecache2-1.0.0 logilab-common-1.1.0 mock-1.0.1 ndg-httpsclient-0.4.0 nose-1.3.7 nosexcover-1.0.10 ordereddict-1.1 parsedatetime-1.5 pep8-1.7.0 pkginfo-1.2.1 pluggy-0.3.1 psutil-3.4.2 py-1.4.31 pyasn1-0.1.9 pycparser-2.14 pylint-1.4.2 pyparsing-2.0.7 pyrfc3339-1.0 python-augeas-0.5.0 python2-pythondialog-3.3.0 pytz-2015.7 repoze.sphinx.autointerface-0.7.1 requests-2.9.1 requests-toolbelt-0.5.1 six-1.10.0 snowballstemmer-1.2.1 sphinx-rtd-theme-0.1.9 sphinxcontrib-programoutput-0.8 tox-2.3.1 traceback2-1.4.0 twine-1.6.5 unittest2-1.1.0 virtualenv-14.0.0 websocket-client-0.35.0 werkzeug-0.11.3 wheel-0.26.0 zope.component-4.2.2 zope.event-4.1.0 zope.interface-4.1.3
[centos@54.86.84.148] out: /home/centos/letsencrypt/venv/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
[centos@54.86.84.148] out:   InsecurePlatformWarning
[centos@54.86.84.148] out: + set +x
[centos@54.86.84.148] out: Please run the following command to activate developer environment:
[centos@54.86.84.148] out: source venv/bin/activate
[centos@54.86.84.148] out: + sudo venv/bin/letsencrypt -v --debug --text --agree-dev-preview --agree-tos --renew-by-default --redirect --register-unsafely-without-email --domain ec2-54-86-84-148.compute-1.amazonaws.com --server http://172.31.54.176:4000/directory
[centos@54.86.84.148] out: /home/centos/letsencrypt/venv/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
[centos@54.86.84.148] out:   DeprecationWarning
[centos@54.86.84.148] out: Use of --agree-dev-preview is deprecated.
[centos@54.86.84.148] out: 2016-01-22 00:30:57,413:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
[centos@54.86.84.148] out: [31m2016-01-22 00:30:57,754:WARNING:letsencrypt.client:Registering without email![0m
[centos@54.86.84.148] out: 2016-01-22 00:30:58,550:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.31.54.176
[centos@54.86.84.148] out: 2016-01-22 00:30:58,556:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.31.54.176
[centos@54.86.84.148] out: 2016-01-22 00:30:58,564:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.31.54.176
[centos@54.86.84.148] out: 2016-01-22 00:30:58,589:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.31.54.176
[centos@54.86.84.148] out: 2016-01-22 00:30:58,604:INFO:letsencrypt.reporter:Reporting to user: Your account credentials have been saved in your Let's Encrypt configuration directory at /etc/letsencrypt. You should make a secure backup of this folder now. This configuration directory will also contain certificates and private keys obtained by Let's Encrypt so making regular backups of this folder is ideal.
[centos@54.86.84.148] out: 2016-01-22 00:30:58,756:INFO:letsencrypt.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0000_key-letsencrypt.pem
[centos@54.86.84.148] out: 2016-01-22 00:30:58,759:INFO:letsencrypt.crypto_util:Creating CSR: /etc/letsencrypt/csr/0000_csr-letsencrypt.pem
[centos@54.86.84.148] out: 2016-01-22 00:30:58,764:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.31.54.176
[centos@54.86.84.148] out: 2016-01-22 00:30:58,789:INFO:letsencrypt.auth_handler:Performing the following challenges:
[centos@54.86.84.148] out: 2016-01-22 00:30:58,789:INFO:letsencrypt.auth_handler:tls-sni-01 challenge for ec2-54-86-84-148.compute-1.amazonaws.com
[centos@54.86.84.148] out: 2016-01-22 00:30:59,247:INFO:letsencrypt.reverter:The Let's Encrypt client has not saved any backups of your configuration
[centos@54.86.84.148] out: 2016-01-22 00:31:02,312:INFO:letsencrypt.auth_handler:Waiting for verification...
[centos@54.86.84.148] out: 2016-01-22 00:31:02,407:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.31.54.176
[centos@54.86.84.148] out: 2016-01-22 00:31:05,452:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.31.54.176
[centos@54.86.84.148] out: 2016-01-22 00:31:05,463:INFO:letsencrypt.reporter:Reporting to user: The following errors were reported by the server:
[centos@54.86.84.148] out: 
[centos@54.86.84.148] out: Domain: ec2-54-86-84-148.compute-1.amazonaws.com
[centos@54.86.84.148] out: Type:   urn:acme:error:unauthorized
[centos@54.86.84.148] out: Detail: Correct zName not found for TLS SNI challenge. Found 
[centos@54.86.84.148] out: 2016-01-22 00:31:05,464:INFO:letsencrypt.auth_handler:Cleaning up challenges
[centos@54.86.84.148] out: 2016-01-22 00:31:05,499:INFO:letsencrypt.reverter:The Let's Encrypt client has not saved any backups of your configuration
[centos@54.86.84.148] out: Traceback (most recent call last):
[centos@54.86.84.148] out:   File "venv/bin/letsencrypt", line 9, in <module>
[centos@54.86.84.148] out:     load_entry_point('letsencrypt', 'console_scripts', 'letsencrypt')()
[centos@54.86.84.148] out:   File "/home/centos/letsencrypt/letsencrypt/cli.py", line 1405, in main
[centos@54.86.84.148] out:     return args.func(args, config, plugins)
[centos@54.86.84.148] out:   File "/home/centos/letsencrypt/letsencrypt/cli.py", line 559, in run
[centos@54.86.84.148] out:     lineage = _auth_from_domains(le_client, config, domains)
[centos@54.86.84.148] out:   File "/home/centos/letsencrypt/letsencrypt/cli.py", line 404, in _auth_from_domains
[centos@54.86.84.148] out:     lineage = le_client.obtain_and_enroll_certificate(domains)
[centos@54.86.84.148] out:   File "/home/centos/letsencrypt/letsencrypt/client.py", line 283, in obtain_and_enroll_certificate
[centos@54.86.84.148] out:     certr, chain, key, _ = self.obtain_certificate(domains)
[centos@54.86.84.148] out:   File "/home/centos/letsencrypt/letsencrypt/client.py", line 266, in obtain_certificate
[centos@54.86.84.148] out:     return self._obtain_certificate(domains, csr) + (key, csr)
[centos@54.86.84.148] out:   File "/home/centos/letsencrypt/letsencrypt/client.py", line 224, in _obtain_certificate
[centos@54.86.84.148] out:     authzr = self.auth_handler.get_authorizations(domains)
[centos@54.86.84.148] out:   File "/home/centos/letsencrypt/letsencrypt/auth_handler.py", line 84, in get_authorizations
[centos@54.86.84.148] out:     self._respond(cont_resp, dv_resp, best_effort)
[centos@54.86.84.148] out:   File "/home/centos/letsencrypt/letsencrypt/auth_handler.py", line 142, in _respond
[centos@54.86.84.148] out:     self._poll_challenges(chall_update, best_effort)
[centos@54.86.84.148] out:   File "/home/centos/letsencrypt/letsencrypt/auth_handler.py", line 204, in _poll_challenges
[centos@54.86.84.148] out:     raise errors.FailedChallenges(all_failed_achalls)
[centos@54.86.84.148] out: FailedChallenges: Failed authorization procedure. ec2-54-86-84-148.compute-1.amazonaws.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Correct zName not found for TLS SNI challenge. Found 
[centos@54.86.84.148] out: 
[centos@54.86.84.148] out: [1m
[centos@54.86.84.148] out: IMPORTANT NOTES:
[centos@54.86.84.148] out: [0m - The following errors were reported by the server:
[centos@54.86.84.148] out: 
[centos@54.86.84.148] out:    Domain: ec2-54-86-84-148.compute-1.amazonaws.com
[centos@54.86.84.148] out:    Type:   urn:acme:error:unauthorized
[centos@54.86.84.148] out:    Detail: Correct zName not found for TLS SNI challenge. Found
[centos@54.86.84.148] out:  - Your account credentials have been saved in your Let's Encrypt
[centos@54.86.84.148] out:    configuration directory at /etc/letsencrypt. You should make a
[centos@54.86.84.148] out:    secure backup of this folder now. This configuration directory will
[centos@54.86.84.148] out:    also contain certificates and private keys obtained by Let's
[centos@54.86.84.148] out:    Encrypt so making regular backups of this folder is ideal.
[centos@54.86.84.148] out: + '[' 1 -ne 0 ']'
[centos@54.86.84.148] out: + FAIL=1
[centos@54.86.84.148] out: + '[' centos = ubuntu ']'
[centos@54.86.84.148] out: + echo Not running hackish apache tests on centos
[centos@54.86.84.148] out: Not running hackish apache tests on centos
[centos@54.86.84.148] out: + '[' 0 -ne 0 ']'
[centos@54.86.84.148] out: + '[' 1 = 1 ']'
[centos@54.86.84.148] out: + exit 1
[centos@54.86.84.148] out: 

ami-57cd8732 - centos6 FAIL
```
@joohoi any thoughts on this?

**Comment by bmw** [comment]
Confirmed that changes to the Apache config are still reverted properly. Tested successfully on Debian 7, but got #2259 on Ubuntu 12.04.

**Comment by bmw** [comment]
I think we probably want this regardless of CentOS failures as it solves at least a subset of the Apache 2.2 problems. There may be problems on other systems and we may want to disable Apache 2.2 again before doing the 0.3.0 release, but this is at least a partial fix for #2228.

**Comment by pde** [comment]
@SwartzCr what are your conclusions from research on that AWS Centos 6 image?

**Comment by pde** [comment]
We should probably have merged this on Friday :/.  Doing so now...

**Comment by SwartzCr** [comment]
The issue with CentOS seems to be that <IfModule mod_ssl.c> doesn't work, and instead you need LoadModule ssl_module modules/mod_ssl.so

**Pull request merged**
