### PR TITLE
Remove Outdated Challenges from ACME

### LINKED ISSUE #1304: Continuity Authenticator
This is a relic from the old spec, over complicate things, and should be removed.

### PR DESCRIPTION
**Pull request by bmw**
Fixes #1304 and builds on #2585 and #2587.

This PR removes continuity challenges from ACME as well as outdated challenges such as `ProofOfPossession` and `RecoveryContact`. While these challenges exist in ACME in some form, their current implementations are outdated and should likely be redesigned in the future.

With this change I also removed, `other.py` which was only used by `ProofOfPossession` and the `DVChallenge` class, whose purpose is now unnecessary and no longer exists in the ACME spec.

@kuba: If you have time to review this (only the ACME changes are relevant to this PR), I'd appreciate it!

### CODE REVIEW

**Comment by pde** [comment]
LGTM.

**Comment by kuba** [comment]
I'll look at it this weekend

**Comment by kuba** [comment]
LGTM

**Comment by bmw** [comment]
Thanks @kuba!

**Pull request merged**
