### PR TITLE
Add bootstrap for OpenBSD

### PR DESCRIPTION
**Pull request by delan**

### CODE REVIEW

**Comment by pde** [comment]
@smutt @sboyettedh would either of you like to review this?  Some fraction of OpenBSD users now have packages, but it's probably fine to offer experimental letsencrpt-auto support too.

**Comment by pde** [comment]
Also, if this is good, a reminder that we should close #1175.

**Comment by smutt** [comment]
I no longer have any domains that need https so I can't test this. I ended up using letsencrypt-nosudo.

Thanks very much for doing this work. Your efforts will increase adoption of HTTPS.

**Comment by erikrose** [comment]
We now have official OpenBSD packages, which can integrate with the system better than le-auto. If there's a compelling reason to add le-auto support regardless, please reopen.

**Pull request closed without merging**
