### PR TITLE
Webroot permissions

### LINKED ISSUE #1795: Webroot breaks for non-root due to chown
Hi,

Today I'm trying out letsencrypt and stumbled upon that using webroot breaks when not using root due to a chown on line 72 of letsencrypt/plugins/webroot.py:

```
 49     def prepare(self):  # pylint: disable=missing-docstring
 50         path_map = self.conf("map")
 51
 52         if not path_map:
 53             raise errors.PluginError("--{0} must be set".format(
 54                 self.option_name("path")))
 55         for name, path in path_map.items():
 56             if not os.path.isdir(path):
 57                 raise errors.PluginError(path + " does not exist or is not a directory")
 58             self.full_roots[name] = os.path.join(path, challenges.HTTP01.URI_ROOT_PATH)
 59
 60             logger.debug("Creating root challenges validation dir at %s",
 61                          self.full_roots[name])
 62             try:
 63                 os.makedirs(self.full_roots[name])
 64                 # Set permissions as parent directory (GH #1389)
 65                 # We don't use the parameters in makedirs because it
 66                 # may not always work
 67                 # https://stackoverflow.com/questions/5231901/permission-problems-when-creating-a-dir-with-os-makedirs-python
 68                 stat_path = os.stat(path)
 69                 filemode = stat.S_IMODE(stat_path.st_mode)
 70                 os.chmod(self.full_roots[name], filemode)
 71                 # Set owner and group, too
 72                 os.chown(self.full_roots[name], stat_path.st_uid,
 73                           stat_path.st_gid)
 74
 75             except OSError as exception:
 76                 if exception.errno != errno.EEXIST:
 77                     raise errors.PluginError(
 78                         "Couldn't create root for {0} http-01 "
 79                         "challenge responses: {1}", name, exception)
```

It tries to set the ownership of the directory to the owner of the parent. So currently to bypass this issue either the webroot must be chown'd to the letsencrypt user, or the script needs to be run as root. Neither of which are satisfactory solutions. Is chown at all neccesary when letsencrypt is not run as root?

### PR DESCRIPTION
**Pull request by bmw**
Supersedes #1807 and fixes #1795.

### CODE REVIEW

**Comment by lucasRolff** [comment]
After this was merged, it means that servers that prevents reading files owned by other users (also known as symlink attacks) - they'll not be able to validate anymore due to removed code here: https://github.com/letsencrypt/letsencrypt/pull/1875/files#diff-522ab130649a0ce14df40114d4ccd0b5L109 

Maybe it should be added back (in a try/except block) - or we should be able to pass an argument with the uid/gid we want to use for the challenge files, else this prevents us for issuing let's encrypt certificates on all our shared hosting boxes.

**Comment by kuba** [comment]
If you're on shared hosting box how do you get root? Which servers "that prevent reading (...)" do you mean? Web servers? Which attacks do you mean?

**Comment by lucasRolff** [comment]
@kuba - I as a system administrator - that wants to offer letsencrypt to my customers.

Basically if you run multiple users on a server, you often want to prevent things from happening, you can either do it by using software like CloudLinux which creates a virtual environment for each user, or you can do other things like installing some extra code in Apache to prevent e.g. a symlink vulnerability in Apache.

Basically in Apache if you enable `SymLinksIfOwnerMatch` and `FollowSymlinks` in Apache you become vulerable to a race condition through symlinks, which allows a user (attacker) to create a symlink to another users file, and he will be able to read it.

To prevent this you can patch apache so it cannot read other users files (which in a shared environment makes sense anyway), since the challenge files are created by root and is owned by root, it means the challenge validation will fail because apache (or any other web-server or server software preventing the webserver) from reading files in the www-folder to read files not owned by the vhost user, or apache/nginx/www-data user will simply fail.

Likewise if you would run with selinux which is very strict about ownership and permissions on folders in /var/www it could cause the webserver being prevented from reading the files.

So to be able (as a shared host) or people protecting in various ways, we would need the possibility to be able to decide who the files should be owned as, or inherit from the parent directly where the file are located.

**Comment by ZeusF1** [comment]
@bmw 
Why did validation files no longer set chown?

I have an issue on Centos6 with with, when permissions are set incorrectly, and ownership for files is root.

Directories have correct permissions, but not a files.

I made short test how permissions works:

` cat test3.py
import os
old_mask = os.umask (022)
fh3 = open ("test3.txt", "w")
os.umask (0)
fh4 = open ("test4.txt", "w")
os.umask (old_mask)
fh3.close()
fh4.close()`

`cat test.py
import os
oldmask = os.umask (022)
fh1 = os.open ("test1.txt", os.O_CREAT, 0o777)
fh2 = os.open ("test2.txt", os.O_CREAT, 0o022)
os.umask (oldmask)
os.close (fh1)
os.close (fh2)`

Result will be:

```
-rwxr-x---+  1 root         root            0 Nov  2 12:47 test1.txt
----------+  1 root         root            0 Nov  2 12:47 test2.txt
-rw-r-----+  1 root         root            0 Nov  2 12:46 test3.txt
-rw-r-----+  1 root         root            0 Nov  2 12:46 test4.txt
```

Just as same as for https://community.letsencrypt.org/t/webroot-plugin-wrong-permission-on-validation-files-nginx-403-error/21728

Any ideas how to fix that or set ownership? ?

**Pull request merged**
