### PR TITLE
PyInstaller setup (fixes #334).

### LINKED ISSUE #334: pyinstaller
@jezdez suggested using http://www.pyinstaller.org/ for binary distribution

### PR DESCRIPTION
**Pull request by kuba**
That's an early preview for binary distribution using http://pyinstaller.org. `cd pyi && make clean all && ./dist/letsencrypt --help`! (Note that this binary is totally separate from what's in `./dist/folder` and you can freely move it around). See `README` for full instructions.

### CODE REVIEW

**Comment by pde** [comment]
@felixrieseberg could you take a loot to see whether this might be a good method to produce a simple .exe installer for Windows users?

**Comment by felixrieseberg** [comment]
That would actually be fantastic, if it worked cleanly - and could potentially revive the whole "let's do this on Windows" thing. I'll check.

**Comment by jdkasten** [comment]
Hooray!  This worked for me!  I did have to run
pip install git+https://github.com/pyinstaller/pyinstaller.git@9d0e0ad4c1c02964bbff86edbf7400cd40958b1a#egg=pyinstaller

Which I found here https://github.com/pyca/cryptography/issues/2039  (I assume that is what you meant in your instructions)

**Comment by douglasmccormickjr** [comment]
Hi Everyone,

Was @jdkasten able to get this to work on a Windows machine after the pip install git+yada_yada or did he get it to work elsewhere?

Also, following the instructions/information on
https://github.com/pyca/cryptography/issues/2039 didn't give me the exact plan of attack/method to rectify the issue.  Could someone make a guide or point me to a resource that can clear up this confusion.

Some background on my project (Windows7 build/target desktop app, using python2.7.10, pySide standalone app [single executable] including these python crypto libs/modules (1) from cryptography.fernet import Fernet (2) from Crypto.Cipher import AES and (3) from Crypto import Random)

Thanks in advance!
-Doug Jr.

**Comment by kuba** [comment]
It's been 40 days since submission (and much more since I started working on this). @pde, could you please finally review and merge? It doesn't affect any core code, but it makes it easier for me to develop further functionality against latest `master` without having to merge over and over again. Moreover, we could build test binaries alongside dev releases, to see if it's a feasible distribution method. Thanks in advance!

**Comment by pde** [comment]
Sorry, I was waiting for @jdkasten to confirm that it was Windows he tested on...

**Comment by kuba** [comment]
It works on Linux. Does it matter if it's tested on Windows? If it doesn't work, then someone will prepare a follow-up PR.

**Comment by pde** [comment]
I don't think we'll be distributing binary linux installers; distro packaging or pip are the right methods on those platforms and all our energy should be spent on those.   One clear reason to support PyInstaller is if/when it gets us a sensible Windows .exe.  I don't know about OS X.

**Comment by pde** [comment]
@felixrieseberg James tells me he only tested on linux.  Any chance you can try it out on Windows?  If not I'll ping some of the other folks who've expressed interest in the Windows porting effort.

**Comment by felixrieseberg** [comment]
I'm having a lot of trouble so far - I tried a few things, but `make` doesn't even cooperate :/ This is a great effort, but I doubt that it'll get us all that closer to Let's Encrypt on Windows (which wasn't the goal, so this is still great).

**Comment by kuba** [comment]
@felixrieseberg, what were problems exactly? I can try to help. You can also reach me on IRC (Freenode, #letesncrypt, Kuba).

**Comment by L1ghtn1ng** [comment]
What may do the trick for windows is py2exe. Give that a spin then and fingers crossed we should be good. Just putting my 2 cents out there for consideration.

**Comment by kuba** [comment]
I've built `0.0.0.dev20151030` based on PyPI release, on my sid x64 box. Tested on **fresh** (no apt-get/yum/dnf!) DO droplets:
- Ubuntu 15.10 x64: `--text` **works**, dialog **works** after `apt-get install dialog`
- Ubuntu 14.04 x64: `--text` **works**, dialog **works** after `apt-get install dialog`
- CentOS 7.1 x64, CentOS Linux release 7.1.1503 (Core); `--text` **works**, dialog interface (after `yum install dialog`) ends in`DialogTerminatedBySignal`
- CentOS 6.7 x64, CentOS release 6.7 (Final), crashes with `./foo: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by /tmp/_MEI8TpnHv/libz.so.1)`
- CentOS 5.10 x64 crashes with `./letsencrypt-0.0.0.dev20151030: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by /tmp/_MEIoAE3uI/libz.so.1)`
- squeeze **x32** doesn't work (as expected)

**Comment by kuba** [comment]
Also, iwmrby tested it on fresh Arch.

**Comment by pde** [comment]
Closing this PR for now; it would be a mistake to try to support an additional install method before public beta.  I hadn't seen the [portability test results](https://github.com/letsencrypt/letsencrypt/pull/715#issuecomment-152870578) above until now but they largely align with my expectation that this approach would expose us to new porting work that isn't prudent with so many other tickets to get through.

**Comment by pde** [comment]
If we're getting towards a true 1.0 client, but we continue to have major gaps in packaging that letsencrypt-auto isn't able to cover, I'd be willing to reconsider at that point.

**Pull request closed without merging**
