### PR TITLE
Use printf in place of echo -n

### PR DESCRIPTION
**Pull request by pde**
Closes: #1236

### CODE REVIEW

**Comment by kuba** [comment]
It doesn't close #1236, because:
- it doesn't fix `boootstrap/venv.sh` stuff
- it doesn't fix Manual plugin

**Comment by kuba** [comment]
Otherwise it's good to merge, but please remember to reopen ticket if you don't fix both problems above!

**Comment by devnsec-com** [comment]
Oops, I've created PR #1238 seconds after you created this PR, but I have also fixed `boootstrap/venv.sh` and `letsencrypt/plugins/manual.py` as @kuba said.

**Comment by pde** [comment]
OK, I'll close this one and #1238 can land when it's ready.

**Pull request closed without merging**
