### PR TITLE
Enforce PEP8 checking in ACME [needs revision]

### PR DESCRIPTION
**Pull request by kuba**

### CODE REVIEW

**Comment by kuba** [comment]
That's fun:
```
/home/travis/build/letsencrypt/letsencrypt/pep8.travis.sh: 6: /home/travis/build/letsencrypt/letsencrypt/pep8.travis.sh: pep8: not found
```

https://travis-ci.org/letsencrypt/letsencrypt/jobs/101437278#L689

Are we even running those checks?

**Comment by kuba** [comment]
Of course not, the same error is in previous builds, e.g. https://travis-ci.org/letsencrypt/letsencrypt/jobs/101437278#L689...

**Comment by kuba** [comment]
Fixed above problems in #2141, but not merged here yet.

**Comment by bmw** [comment]
Unfortunately, it looks like since these tests were written `acme` no longer passes `pep8` https://travis-ci.org/letsencrypt/letsencrypt/jobs/108927871 :(

If you fix the problems, ping me and I'll happily merge to prevent problems from landing in master in the future.

**Comment by kuba** [comment]
@bmw, this should be good now (at least according to my local tests)

**Comment by bmw** [comment]
LGTM. Thanks Kuba.

**Pull request merged**
