### PR TITLE
More release enhancements

### PR DESCRIPTION
**Pull request by bmw**
Automatically removes `SIGFILEBALL` after creating signature in `offline-sigrequest.sh`.

### CODE REVIEW

**Comment by pde** [comment]
I tend to think we should leave that around as a record!

**Comment by bmw** [comment]
But should we leave it in the tree? This is the first release tag that has contained that file.

If we want it in the tree, this PR can be closed.

If we don't want it in the tree, I believe something like this should be merged. If you just want the file locally, maybe we should just update `.gitignore.`

**Comment by pde** [comment]
I'd say it should be in .gitignore.

**Comment by pde** [comment]
Great!

**Pull request merged**
