### PR TITLE
Allow to symlink the letsencrypt-auto script [needs revision]

### PR DESCRIPTION
**Pull request by sttts**
As a user I want to checkout the git repository and symlink the letsencrypt-auto
script into some directory in the path like /usr/local/bin.

### CODE REVIEW

**Comment by pde** [comment]
Thanks for the patch @stts!

At this point in the script we aren't strictly guaranteed to have python available; it may be pulled in by the boostrapping process at some points; we should do this with just the POSIX shell, or do it after bootstrapping.

Secondly, an operation like this is a potential source of breakage, so my instinct was to leave LEA_PATH as it is unless `test -L $LEA_PATH` returns true.

**Comment by stts** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

keliong@naver.com 님께 보내신 메일 <Re: [letsencrypt] Allow to symlink the letsencrypt-auto script [needs revision] (#1768)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by sttts** [comment]
Usually you use "readlink -f" for that, but that doesn't work on OSX due to BSD userland. The `test -L` might work.

**Comment by sttts** [comment]
@pde have replaced the python with some portable bash code.

**Comment by erikrose** [comment]
With the new letsencrypt-auto, landed in #1665, you no longer need a git checkout, so you can place the actual script anywhere you like. Cheers!

**Pull request closed without merging**
