### PR TITLE
Reducing the PyOpenSSL version dep [do not merge]

### PR DESCRIPTION
**Pull request by pde**
Partially addresses #1861, facilitaes packaging on Debian Jessie and possibly Fedora 22, though not [Debian Wheezy](packages.debian.org/python-openssl) or [CentOS 6/7](https://www.rpmfind.net/linux/rpm2html/search.php?query=pyOpenSSL), which have 0.13.

### CODE REVIEW

**Comment by pde** [comment]
This was tested on Debian wheezy.

**Comment by pde** [comment]
I tested this with `venv/bin/pip install pyopenssl==0.14` on a debian wheezy system, and it succeeded in obtaining and replacing certs, which by my reading should have triggered the get_extensions code path.

However I don't think all the unit tests pass with pyopenssl==0.14, so this isn't ready to merge.

**Comment by pde** [comment]
We didn't get a solution to this for 0.1.1, so it will have to catch the 0.2.0 train.

**Comment by kuba** [comment]
Package maintainers can always patch `setup.py` as necessary. Please don't change those version constraints, especially pinning (`==`) to specific version.

**Comment by pde** [comment]
Just to be clear the pin is there to get tox and travis to test that version, and will not be in this PR when it's ready for merging!

**Comment by itamarjp** [comment]
It's interesting to have letsencrypt working with pyopenssl => 0.13 ( to have it packaged for centos 6),  but just changing setup.py isn't the solution.

**Comment by pde** [comment]
Closing this since bmw is doing the real work for this in another branch.

**Pull request closed without merging**
